In [1]:
import sqlite3
from pathlib import Path
import pandas as pd

# Detect project root
current_folder = Path.cwd()

if current_folder.name.lower() == "python_command":
    project_root = current_folder.parent
else:
    project_root = current_folder

dim_database_path = (
    project_root
    / "Datamart"
    / "Dim"
    / "dim_database.db"
)

print("Database path:")
print(dim_database_path.resolve())
print("Database exists:", dim_database_path.exists())

Database path:
C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Datamart\Dim\dim_database.db
Database exists: True

c:\Users\User\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
with sqlite3.connect(dim_database_path) as connection:
    dim_table_list = pd.read_sql_query(
        """
        SELECT name AS table_name
        FROM sqlite_master
        WHERE type = 'table'
        ORDER BY name
        """,
        connection
    )

display(dim_table_list)

                     table_name
0                   dim_account
1         dim_counterparty_role
2  dim_customer_name_confidence
3          dim_transaction_type

In [3]:
dim_tables = {}

with sqlite3.connect(dim_database_path) as connection:
    table_names = pd.read_sql_query(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
        ORDER BY name
        """,
        connection
    )["name"].tolist()

    for table_name in table_names:
        dim_tables[table_name] = pd.read_sql_query(
            f'SELECT * FROM "{table_name}"',
            connection
        )

        print(f"\nTable: {table_name}")
        print("Shape:", dim_tables[table_name].shape)
        display(dim_tables[table_name])

Table: dim_account
Shape: (25, 4)

    account_key account_number        branch     account_type
0             1     0172762156        ท่าพระ          Savings
1             2  053-1-97925-7  NAKHON NAYOK          Savings
2             3  075-8-56737-0     รามอินทรา          Savings
3             4     1022733936        ดินแดง          Savings
4             5  132-1-07885-7  NAKHON NAYOK      Credit Card
5             6     1362714171      รามคำแหง          Savings
6             7     1564296424      พระราม 2          Savings
7             8  168-2-93045-0  NAKHON NAYOK  Current Account
8             9     1922438369       บางพลัด          Savings
9            10     3050XXX982  NAKHON NAYOK          Savings
10           11     3164155931    THE FOURTH          Savings
11           12     3702819949        รังสิต          Savings
12           13     4122310173        วังหิน          Savings
13           14     4142174890       ขอนแก่น          Savings
14           15     4221594268         บางนา          Savings
15           16     4271897496       บางใหญ่          Savings
16           17     4282216316        คลอง 3          Savings
17           18     5194245562        นครปฐม          Savings
18           19     5234735003         ระยอง          Savings
19           20     5692866977      พิษณุโลก          Savings
20           21     6041259598  NAKHON NAYOK          Savings
21           22     6402700634        บางแสน          Savings
22           23     6664038417         โคราช          Savings
23           24     6692694546         พัทยา          Savings
24           25     9597XXX468  NAKHON NAYOK          Savings

Table: dim_counterparty_role
Shape: (8, 2)

   counterparty_role_key counterparty_role_name
0                      1           Counterparty
1                      2         Customer/Payer
2                      3  Possible Counterparty
3                      4         Possible Payee
4                      5     Possible Recipient
5                      6        Possible Sender
6                      7              Recipient
7                      8                 Sender

Table: dim_customer_name_confidence
Shape: (4, 3)

   customer_name_confidence_key customer_name_confidence_name  sort_order
0                             1                          High           1
1                             2                        Medium           2
2                             3                           Low           3
3                             4                 Not Extracted           4

Table: dim_transaction_type
Shape: (17, 2)

    transaction_type_key      transaction_type_name
0                      1            Automatic Debit
1                      2      Automatic Transaction
2                      3                   Bank Fee
3                      4               Cash Deposit
4                      5            Cash Management
5                      6             Cheque Deposit
6                      7        Credit Card Payment
7                      8          Incoming Transfer
8                      9            Interest Income
9                     10  International Transaction
10                    11            Opening Balance
11                    12               Other Credit
12                    13                Other Debit
13                    14          Outgoing Transfer
14                    15              Sales Receipt
15                    16             Sweep Transfer
16                    17                Tax Payment

In [4]:

import sqlite3
from pathlib import Path
import pandas as pd

# Detect project root
current_folder = Path.cwd()

if current_folder.name.lower() == "python_command":
    project_root = current_folder.parent
else:
    project_root = current_folder

dim_database_path = (
    project_root
    / "Datamart"
    / "Dim"
    / "dim_database.db"
)

staging_database_path = (
    project_root
    / "Datamart"
    / "Staging"
    / "staging_bank_statement_2026.db"
)

print("DIM database:", dim_database_path.resolve())
print("Staging database:", staging_database_path.resolve())

DIM database: C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Datamart\Dim\dim_database.db
Staging database: C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Datamart\Staging\staging_bank_statement_2026.db

In [5]:
with sqlite3.connect(staging_database_path) as connection:
    staging_bank_df = pd.read_sql_query(
        """
        SELECT *
        FROM staging_bank_statement_2026
        """,
        connection
    )

print("Staging shape:", staging_bank_df.shape)
display(staging_bank_df.head())

Staging shape: (20491, 13)

,bank,account_number,transaction_date,transaction_time,withdrawal,deposit,outstanding_balance,transaction_type,transaction_type_standard,description_clean,customer_name,counterparty_role,customer_name_confidence
0,BBL,3050XXX982,2026-01-03,03:01,NaN,43435.19,663072.27,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,Not Extracted
1,BBL,3050XXX982,2026-01-04,03:00,NaN,110100.82,773173.09,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,Not Extracted
2,BBL,3050XXX982,2026-01-05,03:00,NaN,17269.82,790442.91,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,Not Extracted
3,BBL,3050XXX982,2026-01-05,04:01,NaN,301.72,790744.63,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,Not Extracted
4,BBL,3050XXX982,2026-01-05,09:03,679.45,NaN,789385.73,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,Not Extracted

In [6]:
with sqlite3.connect(dim_database_path) as connection:
    dim_account = pd.read_sql_query(
        "SELECT * FROM dim_account",
        connection
    )

    dim_transaction_type = pd.read_sql_query(
        "SELECT * FROM dim_transaction_type",
        connection
    )

    dim_counterparty_role = pd.read_sql_query(
        "SELECT * FROM dim_counterparty_role",
        connection
    )

    dim_customer_name_confidence = pd.read_sql_query(
        "SELECT * FROM dim_customer_name_confidence",
        connection
    )

In [7]:
print("dim_account")
display(dim_account.head())

print("dim_transaction_type")
display(dim_transaction_type.head())

print("dim_counterparty_role")
display(dim_counterparty_role.head())

print("dim_customer_name_confidence")
display(dim_customer_name_confidence.head())

dim_account

   account_key account_number        branch account_type
0            1     0172762156        ท่าพระ      Savings
1            2  053-1-97925-7  NAKHON NAYOK      Savings
2            3  075-8-56737-0     รามอินทรา      Savings
3            4     1022733936        ดินแดง      Savings
4            5  132-1-07885-7  NAKHON NAYOK  Credit Card

dim_transaction_type

   transaction_type_key  transaction_type_name
0                     1        Automatic Debit
1                     2  Automatic Transaction
2                     3               Bank Fee
3                     4           Cash Deposit
4                     5        Cash Management

dim_counterparty_role

   counterparty_role_key counterparty_role_name
0                      1           Counterparty
1                      2         Customer/Payer
2                      3  Possible Counterparty
3                      4         Possible Payee
4                      5     Possible Recipient

dim_customer_name_confidence

   customer_name_confidence_key customer_name_confidence_name  sort_order
0                             1                          High           1
1                             2                        Medium           2
2                             3                           Low           3
3                             4                 Not Extracted           4

In [8]:
staging_bank_df["account_number"] = (
    staging_bank_df["account_number"]
    .astype("string")
    .str.strip()
)

dim_account["account_number"] = (
    dim_account["account_number"]
    .astype("string")
    .str.strip()
)

staging_bank_df["transaction_type_standard"] = (
    staging_bank_df["transaction_type_standard"]
    .astype("string")
    .str.strip()
)

dim_transaction_type["transaction_type_name"] = (
    dim_transaction_type["transaction_type_name"]
    .astype("string")
    .str.strip()
)

staging_bank_df["counterparty_role"] = (
    staging_bank_df["counterparty_role"]
    .astype("string")
    .str.strip()
)

dim_counterparty_role["counterparty_role_name"] = (
    dim_counterparty_role["counterparty_role_name"]
    .astype("string")
    .str.strip()
)

staging_bank_df["customer_name_confidence"] = (
    staging_bank_df["customer_name_confidence"]
    .astype("string")
    .str.strip()
)

dim_customer_name_confidence["customer_name_confidence_name"] = (
    dim_customer_name_confidence["customer_name_confidence_name"]
    .astype("string")
    .str.strip()
)

In [9]:
mapped_bank_df = staging_bank_df.copy()

# Map account dimension
mapped_bank_df = mapped_bank_df.merge(
    dim_account[
        [
            "account_key",
            "account_number",
            "branch",
            "account_type"
        ]
    ],
    on="account_number",
    how="left",
    validate="many_to_one"
)

# Map transaction type dimension
mapped_bank_df = mapped_bank_df.merge(
    dim_transaction_type[
        [
            "transaction_type_key",
            "transaction_type_name"
        ]
    ],
    left_on="transaction_type_standard",
    right_on="transaction_type_name",
    how="left",
    validate="many_to_one"
)

# Map counterparty role dimension
mapped_bank_df = mapped_bank_df.merge(
    dim_counterparty_role[
        [
            "counterparty_role_key",
            "counterparty_role_name"
        ]
    ],
    left_on="counterparty_role",
    right_on="counterparty_role_name",
    how="left",
    validate="many_to_one"
)

# Map confidence dimension
mapped_bank_df = mapped_bank_df.merge(
    dim_customer_name_confidence[
        [
            "customer_name_confidence_key",
            "customer_name_confidence_name"
        ]
    ],
    left_on="customer_name_confidence",
    right_on="customer_name_confidence_name",
    how="left",
    validate="many_to_one"
)

print("Mapped shape:", mapped_bank_df.shape)
display(mapped_bank_df.head())

Mapped shape: (20491, 22)

,bank,account_number,transaction_date,transaction_time,withdrawal,deposit,outstanding_balance,transaction_type,transaction_type_standard,description_clean,...,customer_name_confidence,account_key,branch,account_type,transaction_type_key,transaction_type_name,counterparty_role_key,counterparty_role_name,customer_name_confidence_key,customer_name_confidence_name
0,BBL,3050XXX982,2026-01-03,03:01,NaN,43435.19,663072.27,Automatic,Automatic Transaction,BBL.CARD,...,Not Extracted,10,NAKHON NAYOK,Savings,2,Automatic Transaction,NaN,<NA>,4,Not Extracted
1,BBL,3050XXX982,2026-01-04,03:00,NaN,110100.82,773173.09,Automatic,Automatic Transaction,BBL.CARD,...,Not Extracted,10,NAKHON NAYOK,Savings,2,Automatic Transaction,NaN,<NA>,4,Not Extracted
2,BBL,3050XXX982,2026-01-05,03:00,NaN,17269.82,790442.91,Automatic,Automatic Transaction,BBL.CARD,...,Not Extracted,10,NAKHON NAYOK,Savings,2,Automatic Transaction,NaN,<NA>,4,Not Extracted
3,BBL,3050XXX982,2026-01-05,04:01,NaN,301.72,790744.63,Automatic,Automatic Transaction,BBL.CARD,...,Not Extracted,10,NAKHON NAYOK,Savings,2,Automatic Transaction,NaN,<NA>,4,Not Extracted
4,BBL,3050XXX982,2026-01-05,09:03,679.45,NaN,789385.73,Automatic,Automatic Transaction,BBL.CARD,...,Not Extracted,10,NAKHON NAYOK,Savings,2,Automatic Transaction,NaN,<NA>,4,Not Extracted

In [10]:
print("Unmatched account keys:")
display(
    mapped_bank_df.loc[
        mapped_bank_df["account_key"].isna(),
        ["bank", "account_number"]
    ]
    .drop_duplicates()
    .sort_values(["bank", "account_number"])
)

Unmatched account keys:

Empty DataFrame
Columns: [bank, account_number]
Index: []

In [11]:
final_columns = [
    "bank",
    "account_key",
    "account_number",
    "branch",
    "account_type",
    "transaction_date",
    "transaction_time",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "transaction_type_key",
    "transaction_type",
    "transaction_type_standard",
    "description_clean",
    "customer_name",
    "counterparty_role_key",
    "counterparty_role",
    "customer_name_confidence_key",
    "customer_name_confidence"
]

mapped_bank_df = mapped_bank_df[
    [
        column
        for column in final_columns
        if column in mapped_bank_df.columns
    ]
].copy()

display(mapped_bank_df.head())
print(mapped_bank_df.dtypes)
print("Final shape:", mapped_bank_df.shape)

,bank,account_key,account_number,branch,account_type,transaction_date,transaction_time,withdrawal,deposit,outstanding_balance,transaction_type_key,transaction_type,transaction_type_standard,description_clean,customer_name,counterparty_role_key,counterparty_role,customer_name_confidence_key,customer_name_confidence
0,BBL,10,3050XXX982,NAKHON NAYOK,Savings,2026-01-03,03:01,NaN,43435.19,663072.27,2,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,<NA>,4,Not Extracted
1,BBL,10,3050XXX982,NAKHON NAYOK,Savings,2026-01-04,03:00,NaN,110100.82,773173.09,2,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,<NA>,4,Not Extracted
2,BBL,10,3050XXX982,NAKHON NAYOK,Savings,2026-01-05,03:00,NaN,17269.82,790442.91,2,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,<NA>,4,Not Extracted
3,BBL,10,3050XXX982,NAKHON NAYOK,Savings,2026-01-05,04:01,NaN,301.72,790744.63,2,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,<NA>,4,Not Extracted
4,BBL,10,3050XXX982,NAKHON NAYOK,Savings,2026-01-05,09:03,679.45,NaN,789385.73,2,Automatic,Automatic Transaction,BBL.CARD,NaN,NaN,<NA>,4,Not Extracted

bank                                str
account_key                       int64
account_number                   string
branch                              str
account_type                        str
transaction_date                    str
transaction_time                    str
withdrawal                      float64
deposit                         float64
outstanding_balance             float64
transaction_type_key              int64
transaction_type                    str
transaction_type_standard        string
description_clean                   str
customer_name                       str
counterparty_role_key           float64
counterparty_role                string
customer_name_confidence_key      int64
customer_name_confidence         string
dtype: object
Final shape: (20491, 19)

In [12]:
final_columns = [
    "bank",
    "account_key",
    "branch",
    "account_type",
    "transaction_date",
    "transaction_time",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "transaction_type_key",
    "description_clean",
    "customer_name",
    "counterparty_role_key",
    "customer_name_confidence_key",
]

mapped_bank_df = mapped_bank_df[
    [
        column
        for column in final_columns
        if column in mapped_bank_df.columns
    ]
].copy()

display(mapped_bank_df.head())
print(mapped_bank_df.columns.tolist())

,bank,account_key,branch,account_type,transaction_date,transaction_time,withdrawal,deposit,outstanding_balance,transaction_type_key,description_clean,customer_name,counterparty_role_key,customer_name_confidence_key
0,BBL,10,NAKHON NAYOK,Savings,2026-01-03,03:01,NaN,43435.19,663072.27,2,BBL.CARD,NaN,NaN,4
1,BBL,10,NAKHON NAYOK,Savings,2026-01-04,03:00,NaN,110100.82,773173.09,2,BBL.CARD,NaN,NaN,4
2,BBL,10,NAKHON NAYOK,Savings,2026-01-05,03:00,NaN,17269.82,790442.91,2,BBL.CARD,NaN,NaN,4
3,BBL,10,NAKHON NAYOK,Savings,2026-01-05,04:01,NaN,301.72,790744.63,2,BBL.CARD,NaN,NaN,4
4,BBL,10,NAKHON NAYOK,Savings,2026-01-05,09:03,679.45,NaN,789385.73,2,BBL.CARD,NaN,NaN,4

['bank', 'account_key', 'branch', 'account_type', 'transaction_date', 'transaction_time', 'withdrawal', 'deposit', 'outstanding_balance', 'transaction_type_key', 'description_clean', 'customer_name', 'counterparty_role_key', 'customer_name_confidence_key']

In [13]:
from pathlib import Path
import pandas as pd

# Detect project root
current_folder = Path.cwd()

if current_folder.name.lower() == "python_command":
    project_root = current_folder.parent
else:
    project_root = current_folder

# Export folder
export_staging_folder = (
    project_root
    / "Export_CSV"
    / "Staging"
)

export_staging_folder.mkdir(
    parents=True,
    exist_ok=True
)

# Final staging columns
final_columns = [
    "bank",
    "account_key",
    "branch",
    "account_type",
    "transaction_date",
    "transaction_time",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "transaction_type_key",
    "description_clean",
    "customer_name",
    "counterparty_role_key",
    "customer_name_confidence_key",
]

staging_export_df = mapped_bank_df[
    [
        column
        for column in final_columns
        if column in mapped_bank_df.columns
    ]
].copy()

# Ensure transaction_date is datetime
staging_export_df["transaction_date"] = pd.to_datetime(
    staging_export_df["transaction_date"],
    errors="coerce"
)

# Export one CSV per year
for year, year_df in staging_export_df.groupby(
    staging_export_df["transaction_date"].dt.year
):
    year = int(year)

    output_path = (
        export_staging_folder
        / f"staging_bank_statement_{year}.csv"
    )

    year_df = year_df.copy()

    year_df["transaction_date"] = (
        year_df["transaction_date"]
        .dt.strftime("%Y-%m-%d")
    )

    year_df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

    print(f"Year: {year}")
    print(f"Rows exported: {len(year_df):,}")
    print(f"CSV: {output_path.resolve()}")

Year: 2026
Rows exported: 20,491
CSV: C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Export_CSV\Staging\staging_bank_statement_2026.csv

In [14]:
from pathlib import Path

# Detect project root
current_folder = Path.cwd()

if current_folder.name.lower() == "python_command":
    project_root = current_folder.parent
else:
    project_root = current_folder

# Export destination
export_dim_folder = project_root / "Export_CSV" / "Dim"
export_dim_folder.mkdir(parents=True, exist_ok=True)

# Dimension DataFrames and output filenames
dimension_exports = {
    "dim_account.csv": dim_account,
    "dim_transaction_type.csv": dim_transaction_type,
    "dim_counterparty_role.csv": dim_counterparty_role,
    "dim_customer_name_confidence.csv": dim_customer_name_confidence,
}

for file_name, dim_df in dimension_exports.items():
    output_path = export_dim_folder / file_name

    dim_df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"Exported {len(dim_df):,} rows "
        f"to {output_path.resolve()}"
    )

Exported 25 rows to C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Export_CSV\Dim\dim_account.csv
Exported 17 rows to C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Export_CSV\Dim\dim_transaction_type.csv
Exported 8 rows to C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Export_CSV\Dim\dim_counterparty_role.csv
Exported 4 rows to C:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Export_CSV\Dim\dim_customer_name_confidence.csv