In [51]:
import pandas as pd
import numpy as np
from pathlib import Path

In [52]:
project_folder = Path.cwd().parent

kbank_folder = project_folder / "Year_End_2026" / "KBANK_Account"
output_folder = project_folder / "Datamart"

output_folder.mkdir(parents=True, exist_ok=True)

print("Current notebook folder:", Path.cwd())
print("KBANK source folder:", kbank_folder)
print("Output folder:", output_folder)
print("KBANK folder exists:", kbank_folder.exists())

Current notebook folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Python_Command
KBANK source folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Year_End_2026\KBANK_Account
Output folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Datamart
KBANK folder exists: True

In [53]:
kbank_files = sorted(kbank_folder.rglob("*.csv"))

print(f"Total CSV files found: {len(kbank_files)}")

for file in kbank_files:
    print(file.relative_to(kbank_folder))

Total CSV files found: 19
Apr\กสิกร-กระแสรายวัน.csv
Apr\กสิกร-บัตรเครดิต.csv
Apr\กสิกร-รามอินทรา.csv
Apr\กสิกร-ออมทรัพย์.csv
Feb\053.csv
Feb\075.csv
Feb\132.csv
Feb\168.csv
Jan\resultFile_20260205_152531.csv
Jan\resultFile_20260205_152645.csv
Jan\resultFile_20260205_152807.csv
June\053-ออมทรัพย์.csv
June\075-รามอินทรา.csv
June\132-บัตรเครดิต.csv
June\168-กระแสรายวัน.csv
May\กสิกร กระแส.csv
May\กสิกร บัตรเครดิต.csv
May\กสิกร รามอินทรา.csv
May\กสิกร ออมทรัพย์.csv

In [54]:
from pathlib import Path

# Current notebook folder:
# Bank_Account_Project/Python_Command

notebook_folder = Path.cwd()
project_folder = notebook_folder.parent

kbank_folder = (
    project_folder
    / "Year_End_2026"
    / "KBANK_Account"
)

output_folder = project_folder / "Datamart"
output_folder.mkdir(parents=True, exist_ok=True)

print("Notebook folder:", notebook_folder)
print("Project folder:", project_folder)
print("KBANK folder:", kbank_folder)
print("KBANK folder exists:", kbank_folder.exists())

Notebook folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Python_Command
Project folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project
KBANK folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Year_End_2026\KBANK_Account
KBANK folder exists: True

In [55]:
supported_extensions = {".csv", ".xls", ".xlsx"}

kbank_files = sorted(
    file
    for file in kbank_folder.rglob("*")
    if file.is_file()
    and file.suffix.lower() in supported_extensions
    and not file.name.startswith("~$")
)

print(f"Total KBANK files found: {len(kbank_files)}")

for file in kbank_files:
    print(file.relative_to(kbank_folder))

Total KBANK files found: 23
Apr\กสิกร-กระแสรายวัน.csv
Apr\กสิกร-บัตรเครดิต.csv
Apr\กสิกร-รามอินทรา.csv
Apr\กสิกร-ออมทรัพย์.csv
Feb\053.csv
Feb\075.csv
Feb\132.csv
Feb\168.csv
Jan\resultFile_20260205_152531.csv
Jan\resultFile_20260205_152645.csv
Jan\resultFile_20260205_152807.csv
June\053-ออมทรัพย์.csv
June\075-รามอินทรา.csv
June\132-บัตรเครดิต.csv
June\168-กระแสรายวัน.csv
Mar\กสิกร กระแส.xlsx
Mar\บัตร กสิกร.xlsx
Mar\รามอินทรา.xlsx
Mar\ออมทรัพย์ กสิกร..xlsx
May\กสิกร กระแส.csv
May\กสิกร บัตรเครดิต.csv
May\กสิกร รามอินทรา.csv
May\กสิกร ออมทรัพย์.csv

In [56]:
import pandas as pd

def read_kbank_raw(file_path):
    suffix = file_path.suffix.lower()

    if suffix == ".csv":
        for encoding in ["utf-8-sig", "utf-8", "cp874", "tis-620"]:
            try:
                return pd.read_csv(
                    file_path,
                    header=None,
                    dtype=str,
                    encoding=encoding,
                    sep=",",
                    engine="python",
                    on_bad_lines="skip"
                )
            except UnicodeDecodeError:
                continue

        raise ValueError(
            f"Cannot identify encoding: {file_path}"
        )

    if suffix in {".xls", ".xlsx"}:
        return pd.read_excel(
            file_path,
            header=None,
            dtype=str
        )

    raise ValueError(
        f"Unsupported file type: {file_path.suffix}"
    )

In [57]:
sample_file = kbank_files[0]

print("Sample file:", sample_file)
print("Relative path:", sample_file.relative_to(kbank_folder))

sample_raw = read_kbank_raw(sample_file)

display(sample_raw.head(15))

Sample file: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Year_End_2026\KBANK_Account\Apr\กสิกร-กระแสรายวัน.csv
Relative path: Apr\กสิกร-กระแสรายวัน.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,รายการเดินบัญชีเงินฝากกระแสรายวัน (มีรายละเอียด),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,K-DEPOSIT STATEMENT OF CURRENT ACCOUNT (WITH D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ที่ DD.047 : N26053010320289898705O/2569,หน้าที่ 1/1,NaN,NaN,0264,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,ชื่อบัญชี,บจก. ไอ แฮฟ ซีพียู\n252 ม.4 ต.หนองแสง อ.ปากพลี...,NaN,NaN,NaN,NaN,เลขที่อ้างอิง,NaN,NaN,NaN,26053010320289898705,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,เลขที่บัญชีเงินฝาก,NaN,NaN,NaN,168-2-93045-0,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,รอบระหว่างวันที่,NaN,NaN,NaN,01/04/2026 - 30/04/2026,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,สาขาเจ้าของบัญชี,NaN,NaN,NaN,สาขานครนายก,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ยอดยกไป,NaN,NaN,NaN,NaN,"1,754,024.33"
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,รวมถอนเงิน,NaN,312,NaN,รายการ,"119,642,150.51"
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,รวมฝากเงิน,NaN,70,NaN,รายการ,"111,529,676.00"
10,NaN,วันที่,เวลา/วันที่ ทำรายการ,รายการ,ถอนเงิน,NaN,ฝากเงิน,NaN,ยอดคงเหลือ,NaN,ช่องทาง,NaN,รายละเอียด
11,NaN,01-04-26,NaN,ยอดยกมา,NaN,NaN,NaN,NaN,"9,866,498.84",NaN,NaN,NaN,NaN
12,NaN,01-04-26,10:00,โอนเงิน,"1,354,620.00",NaN,NaN,NaN,"8,511,878.84",NaN,K BIZ,NaN,โอนไป X7000 CCS ASSET II L++
13,NaN,01-04-26,10:00,ค่าธรรมเนียม,120.00,NaN,NaN,NaN,"8,511,758.84",NaN,K BIZ,NaN,รหัสอ้างอิง KCB13011
14,NaN,01-04-26,13:37,โอนเงิน,150.00,NaN,NaN,NaN,"8,511,608.84",NaN,K BIZ,NaN,โอนไป X3740 นาย พงศธร อังกูรอั++

In [58]:
import pandas as pd
import numpy as np
import re

from pathlib import Path
from IPython.display import display


# Notebook อยู่ใน:
# Bank_Account_Project/Python_Command/KBANK.ipynb

notebook_folder = Path.cwd()
project_folder = notebook_folder.parent

kbank_folder = (
    project_folder
    / "Year_End_2026"
    / "KBANK_Account"
)

output_folder = project_folder / "Datamart"
output_folder.mkdir(parents=True, exist_ok=True)

supported_extensions = {".csv", ".xls", ".xlsx"}

kbank_files = sorted(
    file
    for file in kbank_folder.rglob("*")
    if file.is_file()
    and file.suffix.lower() in supported_extensions
    and not file.name.startswith("~$")
)

print("KBANK folder:", kbank_folder)
print("Folder exists:", kbank_folder.exists())
print("Total files found:", len(kbank_files))

for file in kbank_files:
    print(file.relative_to(kbank_folder))

KBANK folder: c:\Users\User\Desktop\Python 100 Days\Bank_Account_Project\Year_End_2026\KBANK_Account
Folder exists: True
Total files found: 23
Apr\กสิกร-กระแสรายวัน.csv
Apr\กสิกร-บัตรเครดิต.csv
Apr\กสิกร-รามอินทรา.csv
Apr\กสิกร-ออมทรัพย์.csv
Feb\053.csv
Feb\075.csv
Feb\132.csv
Feb\168.csv
Jan\resultFile_20260205_152531.csv
Jan\resultFile_20260205_152645.csv
Jan\resultFile_20260205_152807.csv
June\053-ออมทรัพย์.csv
June\075-รามอินทรา.csv
June\132-บัตรเครดิต.csv
June\168-กระแสรายวัน.csv
Mar\กสิกร กระแส.xlsx
Mar\บัตร กสิกร.xlsx
Mar\รามอินทรา.xlsx
Mar\ออมทรัพย์ กสิกร..xlsx
May\กสิกร กระแส.csv
May\กสิกร บัตรเครดิต.csv
May\กสิกร รามอินทรา.csv
May\กสิกร ออมทรัพย์.csv

In [59]:
def read_kbank_raw(file_path):
    suffix = file_path.suffix.lower()

    if suffix == ".csv":
        encodings = [
            "utf-8-sig",
            "utf-8",
            "cp874",
            "tis-620"
        ]

        last_error = None

        for encoding in encodings:
            try:
                return pd.read_csv(
                    file_path,
                    header=None,
                    dtype=str,
                    encoding=encoding,
                    sep=",",
                    engine="python",
                    on_bad_lines="skip"
                )

            except UnicodeDecodeError as error:
                last_error = error

        raise ValueError(
            f"Cannot decode file: {file_path.name}"
        ) from last_error

    if suffix in {".xls", ".xlsx"}:
        return pd.read_excel(
            file_path,
            header=None,
            dtype=str
        )

    raise ValueError(
        f"Unsupported file type: {file_path.suffix}"
    )

In [60]:
def clean_cell(value):
    if pd.isna(value):
        return ""

    return (
        str(value)
        .replace("\n", " ")
        .replace("\r", " ")
        .strip()
    )

In [61]:
def extract_account_number(raw):
    account_labels = [
        "เลขที่บัญชีเงินฝาก",
        "เลขที่บัญชี",
        "บัญชีเงินฝาก"
    ]

    account_pattern = re.compile(
        r"\b\d{3}-\d-\d{5}-\d\b"
    )

    # ตรวจเฉพาะส่วนบนของ Statement
    max_rows = min(len(raw), 30)

    for row_index in range(max_rows):
        for col_index in range(len(raw.columns)):
            cell = clean_cell(
                raw.iat[row_index, col_index]
            )

            if not any(
                label in cell
                for label in account_labels
            ):
                continue

            # กรณีข้อความและเลขบัญชีอยู่ในเซลล์เดียวกัน
            match = account_pattern.search(cell)

            if match:
                return match.group(0)

            # ตรวจเซลล์ทางขวา
            for next_col in range(
                col_index + 1,
                min(col_index + 10, len(raw.columns))
            ):
                candidate = clean_cell(
                    raw.iat[row_index, next_col]
                )

                match = account_pattern.search(candidate)

                if match:
                    return match.group(0)

    # สำรอง: ค้นหารูปแบบเลขบัญชีในส่วนบนทั้งหมด
    for row_index in range(max_rows):
        for col_index in range(len(raw.columns)):
            candidate = clean_cell(
                raw.iat[row_index, col_index]
            )

            match = account_pattern.search(candidate)

            if match:
                return match.group(0)

    return None

In [62]:
def find_transaction_header(raw):
    for row_index in range(len(raw)):
        row_values = (
            raw.iloc[row_index]
            .fillna("")
            .astype(str)
            .map(clean_cell)
        )

        has_date = row_values.eq("วันที่").any()

        has_time = row_values.str.contains(
            r"เวลา|วันที่รายการ",
            regex=True,
            na=False
        ).any()

        has_balance = row_values.str.contains(
            r"ยอดคงเหลือ",
            regex=True,
            na=False
        ).any()

        has_amount = row_values.str.contains(
            r"ถอนเงิน|ฝากเงิน",
            regex=True,
            na=False
        ).any()

        if has_date and (
            has_time
            or has_balance
            or has_amount
        ):
            return row_index

    return None

In [63]:
def normalize_kbank_column(column_name):
    column_name = clean_cell(column_name)

    replacements = {
        "วันที่": "transaction_date",
        "เวลา/ วันที่รายการ": "transaction_time_description",
        "เวลา/วันที่รายการ": "transaction_time_description",
        "เวลา / วันที่รายการ": "transaction_time_description",
        "ถอนเงิน": "withdrawal",
        "ฝากเงิน": "deposit",
        "ยอดคงเหลือ": "outstanding_balance",
        "ช่องทาง": "channel",
        "รายละเอียด": "description"
    }

    return replacements.get(
        column_name,
        column_name
    )

In [64]:
def make_unique_columns(columns):
    unique_columns = []
    column_count = {}

    for index, column in enumerate(columns):
        column = normalize_kbank_column(column)

        if not column:
            column = f"extra_column_{index + 1}"

        if column in column_count:
            column_count[column] += 1
            column = (
                f"{column}_{column_count[column]}"
            )
        else:
            column_count[column] = 0

        unique_columns.append(column)

    return unique_columns

In [65]:
def read_kbank_statement(file_path, root_folder):
    raw = read_kbank_raw(file_path)

    raw = raw.map(clean_cell)

    account_number = extract_account_number(raw)
    header_row = find_transaction_header(raw)

    if header_row is None:
        raise ValueError(
            f"ไม่พบแถวหัวตารางที่มีคำว่า วันที่: "
            f"{file_path.name}"
        )

    header_values = raw.iloc[header_row].tolist()

    # หาคอลัมน์เริ่มต้นที่มีคำว่า วันที่
    start_column = None

    for column_index, value in enumerate(
        header_values
    ):
        if clean_cell(value) == "วันที่":
            start_column = column_index
            break

    if start_column is None:
        raise ValueError(
            f"ไม่พบคอลัมน์ วันที่: {file_path.name}"
        )

    # เก็บตั้งแต่คอลัมน์ วันที่ ไปจนถึงขวาสุด
    transaction_area = raw.iloc[
        header_row:,
        start_column:
    ].copy()

    # ลบเฉพาะคอลัมน์ที่ว่างทั้งหมด
    valid_columns = transaction_area.apply(
        lambda column: (
            column
            .fillna("")
            .astype(str)
            .str.strip()
            .ne("")
            .any()
        )
    )

    transaction_area = transaction_area.loc[
        :,
        valid_columns
    ]

    columns = make_unique_columns(
        transaction_area.iloc[0].tolist()
    )

    df = transaction_area.iloc[1:].copy()
    df.columns = columns
    df = df.reset_index(drop=True)

    df = df.replace(
        {
            "": np.nan,
            "nan": np.nan,
            "NaN": np.nan,
            "None": np.nan
        }
    )

    # ลบแถวที่ว่างทั้งหมด
    df = df.dropna(how="all").copy()

    # เก็บเฉพาะแถว transaction ที่มีวันที่
    if "transaction_date" in df.columns:
        df = df[
            df["transaction_date"].notna()
        ].copy()

    relative_path = file_path.relative_to(
        root_folder
    )

    month_folder = (
        relative_path.parts[0]
        if len(relative_path.parts) > 1
        else None
    )

    # เพิ่มข้อมูลจากส่วนบนของ Statement
    df.insert(0, "bank", "KBANK")
    df.insert(1, "account_number", account_number)
    df.insert(2, "month_folder", month_folder)
    df.insert(3, "source_file", file_path.name)
    df.insert(
        4,
        "source_path",
        str(relative_path)
    )

    return df

In [66]:
all_kbank_data = []
failed_files = []

for file in kbank_files:
    try:
        file_df = read_kbank_statement(
            file_path=file,
            root_folder=kbank_folder
        )

        all_kbank_data.append(file_df)

        account = (
            file_df["account_number"].iloc[0]
            if not file_df.empty
            else None
        )

        print(
            f"OK | "
            f"{file.relative_to(kbank_folder)} | "
            f"Account: {account} | "
            f"Rows: {len(file_df):,}"
        )

    except Exception as error:
        failed_files.append({
            "source_file": str(
                file.relative_to(kbank_folder)
            ),
            "error": str(error)
        })

        print(
            f"FAILED | "
            f"{file.relative_to(kbank_folder)} | "
            f"{error}"
        )

OK | Apr\กสิกร-กระแสรายวัน.csv | Account: 168-2-93045-0 | Rows: 383
OK | Apr\กสิกร-บัตรเครดิต.csv | Account: 132-1-07885-7 | Rows: 88

OK | Apr\กสิกร-รามอินทรา.csv | Account: 075-8-56737-0 | Rows: 176
OK | Apr\กสิกร-ออมทรัพย์.csv | Account: 053-1-97925-7 | Rows: 790
OK | Feb\053.csv | Account: 053-1-97925-7 | Rows: 1,034
OK | Feb\075.csv | Account: 075-8-56737-0 | Rows: 125
OK | Feb\132.csv | Account: 132-1-07885-7 | Rows: 81
OK | Feb\168.csv | Account: 168-2-93045-0 | Rows: 341
OK | Jan\resultFile_20260205_152531.csv | Account: 075-8-56737-0 | Rows: 157
OK | Jan\resultFile_20260205_152645.csv | Account: 132-1-07885-7 | Rows: 88
OK | Jan\resultFile_20260205_152807.csv | Account: 053-1-97925-7 | Rows: 1,116
OK | June\053-ออมทรัพย์.csv | Account: 053-1-97925-7 | Rows: 976
OK | June\075-รามอินทรา.csv | Account: 075-8-56737-0 | Rows: 193
OK | June\132-บัตรเครดิต.csv | Account: 132-1-07885-7 | Rows: 98
OK | June\168-กระแสรายวัน.csv | Account: 168-2-93045-0 | Rows: 391
OK | Mar\กสิกร กระแส.xlsx | Account: 168-2-93045-0 | Rows: 414
OK | Mar\บัตร กสิกร.xlsx | Account: 132-1-07885-7 | Rows: 96
OK | Mar\รามอินทรา.xlsx | Account: 075-8-56737-0 | Rows: 169
OK | Mar\ออมทรัพย์ กสิกร..xlsx | Account: 053-1-97925-7 | Rows: 1,090
OK | May\กสิกร กระแส.csv | Account: 168-2-93045-0 | Rows: 380
OK | May\กสิกร บัตรเครดิต.csv | Account: 132-1-07885-7 | Rows: 101
OK | May\กสิกร รามอินทรา.csv | Account: 075-8-56737-0 | Rows: 151
OK | May\กสิกร ออมทรัพย์.csv | Account: 053-1-97925-7 | Rows: 882

In [67]:
if all_kbank_data:
    kbank_df = pd.concat(
        all_kbank_data,
        ignore_index=True,
        sort=False
    )
else:
    kbank_df = pd.DataFrame()

print("Total rows:", len(kbank_df))
print("Columns:")
print(kbank_df.columns.tolist())

display(kbank_df.head(30))

Total rows: 9320
Columns:
['bank', 'account_number', 'month_folder', 'source_file', 'source_path', 'transaction_date', 'เวลา/วันที่ ทำรายการ', 'รายการ', 'withdrawal', 'deposit', 'outstanding_balance', 'channel', 'description', 'เวลา/ วันที่มีผล']

,bank,account_number,month_folder,source_file,source_path,transaction_date,เวลา/วันที่ ทำรายการ,รายการ,withdrawal,deposit,outstanding_balance,channel,description,เวลา/ วันที่มีผล
0,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,NaN,ยอดยกมา,NaN,NaN,"9,866,498.84",NaN,NaN,NaN
1,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,10:00,โอนเงิน,"1,354,620.00",NaN,"8,511,878.84",K BIZ,โอนไป X7000 CCS ASSET II L++,NaN
2,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,10:00,ค่าธรรมเนียม,120.00,NaN,"8,511,758.84",K BIZ,รหัสอ้างอิง KCB13011,NaN
3,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,150.00,NaN,"8,511,608.84",K BIZ,โอนไป X3740 นาย พงศธร อังกูรอั++,NaN
4,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"1,600.00",NaN,"8,510,008.84",K BIZ,โอนไป X3734 นาย จิรเดช มีกลิ่น++,NaN
5,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"22,790.00",NaN,"8,487,218.84",K BIZ,โอนไป X0706 นาย พชรดนัย เนียม++,NaN
6,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"1,000.00",NaN,"8,486,218.84",K BIZ,โอนไป KTB X3322 นายณัฐพล นิ่มสุวรร++,NaN
7,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"1,100.00",NaN,"8,485,118.84",K BIZ,โอนไป X5893 นาย บุญพิทักษ์ โด++,NaN
8,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,115.00,NaN,"8,485,003.84",K BIZ,โอนไป X3139 นาย วีรพล วงค์น้ำ++,NaN
9,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"36,016.20",NaN,"8,448,987.64",K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++,NaN
10,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"8,287,310.50",NaN,"161,677.14",K BIZ,โอนไป X5356 บมจ. ซินเน็ค (ประเ++,NaN
11,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,13:37,โอนเงิน,"24,950.00",NaN,"136,727.14",K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++,NaN
12,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,23:19,รับเงินจากการขายด้วย Thai QR Payment,NaN,"613,670.00","750,397.14",EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,NaN
13,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,12:31,รับโอนเงิน,NaN,"900,000.00","1,650,397.14",K BIZ,จาก X7370 บริษัท ไอ แฮฟ ซีพี++,NaN
14,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,12:31,รับโอนเงิน,NaN,"1,700,000.00","3,350,397.14",K BIZ,จาก X8857 บจก. ไอ แฮฟ ซีพี++,NaN
15,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,12:31,รับโอนเงิน,NaN,"4,000,000.00","7,350,397.14",K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,NaN
16,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,13:58,โอนเงิน,"3,216,464.19",NaN,"4,133,932.95",K BIZ,โอนไป X9717 บมจ. เอสวีโอ++,NaN
17,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"7,080.00",NaN,"4,126,852.95",K BIZ,โอนไป KTB X8919 เทศบาลเมืองกระทุ่ม++,NaN
18,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"1,000.00",NaN,"4,125,852.95",K BIZ,โอนไป BAY X2413 นาย เติมศักดิ์ จุด++,NaN
19,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"6,900.00",NaN,"4,118,952.95",K BIZ,โอนไป BBL X0707 MR JANCOME HABOU++,NaN
20,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"1,000.00",NaN,"4,117,952.95",K BIZ,โอนไป X1312 นาย ภูรินทร์ พ่วงช++,NaN
21,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"2,085.00",NaN,"4,115,867.95",K BIZ,โอนไป X3866 น.ส. อมรรัตน์ พันเ++,NaN
22,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"4,300.00",NaN,"4,111,567.95",K BIZ,โอนไป X2338 ด.ช. ภัทร์นรินท์ แ++,NaN
23,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,550.00,NaN,"4,111,017.95",K BIZ,โอนไป X0094 นาย ลัญจกร เยื้องท++,NaN
24,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"52,858.00",NaN,"4,058,159.95",K BIZ,"โอนไป X1761 KASET LATEX CO.,LT++",NaN
25,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"7,212.00",NaN,"4,050,947.95",K BIZ,โอนไป X3130 บจก. ไทม์ แอคเซส โ++,NaN
26,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:02,โอนเงิน,"2,000,000.00",NaN,"2,050,947.95",K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,NaN
27,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,14:47,โอนเงิน,"1,500,958.68",NaN,"549,989.27",K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,NaN
28,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,23:18,รับเงินจากการขายด้วย Thai QR Payment,NaN,"348,308.00","898,297.27",EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,NaN
29,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,03-04-26,10:07,รับโอนเงิน,NaN,"3,400,000.00","4,298,297.27",K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,NaN

In [68]:
if "transaction_time_description" in kbank_df.columns:
    extracted = (
        kbank_df[
            "transaction_time_description"
        ]
        .astype("string")
        .str.extract(
            r"^\s*(\d{1,2}:\d{2})?\s*(.*)$"
        )
    )

    kbank_df["transaction_time"] = extracted[0]
    kbank_df["transaction_type"] = (
        extracted[1]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

In [69]:
preferred_columns = [
    "bank",
    "account_number",
    "month_folder",
    "source_file",
    "source_path",
    "transaction_date",
    "transaction_time",
    "transaction_type",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "channel",
    "description"
]

existing_preferred = [
    column
    for column in preferred_columns
    if column in kbank_df.columns
]

other_columns = [
    column
    for column in kbank_df.columns
    if column not in existing_preferred
]

kbank_df = kbank_df[
    existing_preferred + other_columns
]

display(kbank_df.head(30))

,bank,account_number,month_folder,source_file,source_path,transaction_date,withdrawal,deposit,outstanding_balance,channel,description,เวลา/วันที่ ทำรายการ,รายการ,เวลา/ วันที่มีผล
0,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,NaN,NaN,"9,866,498.84",NaN,NaN,NaN,ยอดยกมา,NaN
1,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"1,354,620.00",NaN,"8,511,878.84",K BIZ,โอนไป X7000 CCS ASSET II L++,10:00,โอนเงิน,NaN
2,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,120.00,NaN,"8,511,758.84",K BIZ,รหัสอ้างอิง KCB13011,10:00,ค่าธรรมเนียม,NaN
3,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,150.00,NaN,"8,511,608.84",K BIZ,โอนไป X3740 นาย พงศธร อังกูรอั++,13:37,โอนเงิน,NaN
4,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"1,600.00",NaN,"8,510,008.84",K BIZ,โอนไป X3734 นาย จิรเดช มีกลิ่น++,13:37,โอนเงิน,NaN
5,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"22,790.00",NaN,"8,487,218.84",K BIZ,โอนไป X0706 นาย พชรดนัย เนียม++,13:37,โอนเงิน,NaN
6,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"1,000.00",NaN,"8,486,218.84",K BIZ,โอนไป KTB X3322 นายณัฐพล นิ่มสุวรร++,13:37,โอนเงิน,NaN
7,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"1,100.00",NaN,"8,485,118.84",K BIZ,โอนไป X5893 นาย บุญพิทักษ์ โด++,13:37,โอนเงิน,NaN
8,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,115.00,NaN,"8,485,003.84",K BIZ,โอนไป X3139 นาย วีรพล วงค์น้ำ++,13:37,โอนเงิน,NaN
9,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"36,016.20",NaN,"8,448,987.64",K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++,13:37,โอนเงิน,NaN
10,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"8,287,310.50",NaN,"161,677.14",K BIZ,โอนไป X5356 บมจ. ซินเน็ค (ประเ++,13:37,โอนเงิน,NaN
11,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,"24,950.00",NaN,"136,727.14",K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++,13:37,โอนเงิน,NaN
12,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,01-04-26,NaN,"613,670.00","750,397.14",EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,23:19,รับเงินจากการขายด้วย Thai QR Payment,NaN
13,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,NaN,"900,000.00","1,650,397.14",K BIZ,จาก X7370 บริษัท ไอ แฮฟ ซีพี++,12:31,รับโอนเงิน,NaN
14,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,NaN,"1,700,000.00","3,350,397.14",K BIZ,จาก X8857 บจก. ไอ แฮฟ ซีพี++,12:31,รับโอนเงิน,NaN
15,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,NaN,"4,000,000.00","7,350,397.14",K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,12:31,รับโอนเงิน,NaN
16,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"3,216,464.19",NaN,"4,133,932.95",K BIZ,โอนไป X9717 บมจ. เอสวีโอ++,13:58,โอนเงิน,NaN
17,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"7,080.00",NaN,"4,126,852.95",K BIZ,โอนไป KTB X8919 เทศบาลเมืองกระทุ่ม++,14:02,โอนเงิน,NaN
18,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"1,000.00",NaN,"4,125,852.95",K BIZ,โอนไป BAY X2413 นาย เติมศักดิ์ จุด++,14:02,โอนเงิน,NaN
19,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"6,900.00",NaN,"4,118,952.95",K BIZ,โอนไป BBL X0707 MR JANCOME HABOU++,14:02,โอนเงิน,NaN
20,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"1,000.00",NaN,"4,117,952.95",K BIZ,โอนไป X1312 นาย ภูรินทร์ พ่วงช++,14:02,โอนเงิน,NaN
21,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"2,085.00",NaN,"4,115,867.95",K BIZ,โอนไป X3866 น.ส. อมรรัตน์ พันเ++,14:02,โอนเงิน,NaN
22,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"4,300.00",NaN,"4,111,567.95",K BIZ,โอนไป X2338 ด.ช. ภัทร์นรินท์ แ++,14:02,โอนเงิน,NaN
23,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,550.00,NaN,"4,111,017.95",K BIZ,โอนไป X0094 นาย ลัญจกร เยื้องท++,14:02,โอนเงิน,NaN
24,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"52,858.00",NaN,"4,058,159.95",K BIZ,"โอนไป X1761 KASET LATEX CO.,LT++",14:02,โอนเงิน,NaN
25,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"7,212.00",NaN,"4,050,947.95",K BIZ,โอนไป X3130 บจก. ไทม์ แอคเซส โ++,14:02,โอนเงิน,NaN
26,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"2,000,000.00",NaN,"2,050,947.95",K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,14:02,โอนเงิน,NaN
27,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,"1,500,958.68",NaN,"549,989.27",K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,14:47,โอนเงิน,NaN
28,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,02-04-26,NaN,"348,308.00","898,297.27",EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,23:18,รับเงินจากการขายด้วย Thai QR Payment,NaN
29,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,03-04-26,NaN,"3,400,000.00","4,298,297.27",K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,10:07,รับโอนเงิน,NaN

In [70]:
if "transaction_date" in kbank_df.columns:
    kbank_df["transaction_date"] = pd.to_datetime(
        kbank_df["transaction_date"],
        dayfirst=True,
        errors="coerce"
    )

numeric_columns = [
    "withdrawal",
    "deposit",
    "outstanding_balance"
]

for column in numeric_columns:
    if column in kbank_df.columns:
        kbank_df[column] = (
            kbank_df[column]
            .astype("string")
            .str.replace(",", "", regex=False)
            .str.replace("#####", "", regex=False)
            .str.strip()
            .replace("", pd.NA)
        )

        kbank_df[column] = pd.to_numeric(
            kbank_df[column],
            errors="coerce"
        )

C:\Users\User\AppData\Local\Temp\ipykernel_15152\1468867116.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  kbank_df["transaction_date"] = pd.to_datetime(

In [71]:
sample_account = (
    kbank_df["account_number"]
    .dropna()
    .iloc[0]
)

sample_month = (
    kbank_df.loc[
        kbank_df["account_number"].eq(
            sample_account
        ),
        "month_folder"
    ]
    .dropna()
    .iloc[0]
)

sample_df = kbank_df[
    kbank_df["account_number"].eq(
        sample_account
    )
    & kbank_df["month_folder"].eq(
        sample_month
    )
].copy()

display_columns = [
    "account_number",
    "month_folder",
    "transaction_date",
    "transaction_time",
    "transaction_type",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "channel",
    "description"
]

display(
    sample_df[
        [
            column
            for column in display_columns
            if column in sample_df.columns
        ]
    ].head(50)
)

,account_number,month_folder,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
0,168-2-93045-0,Apr,2026-04-01,<NA>,<NA>,9866498.84,NaN,NaN
1,168-2-93045-0,Apr,2026-04-01,1354620.0,<NA>,8511878.84,K BIZ,โอนไป X7000 CCS ASSET II L++
2,168-2-93045-0,Apr,2026-04-01,120.0,<NA>,8511758.84,K BIZ,รหัสอ้างอิง KCB13011
3,168-2-93045-0,Apr,2026-04-01,150.0,<NA>,8511608.84,K BIZ,โอนไป X3740 นาย พงศธร อังกูรอั++
4,168-2-93045-0,Apr,2026-04-01,1600.0,<NA>,8510008.84,K BIZ,โอนไป X3734 นาย จิรเดช มีกลิ่น++
5,168-2-93045-0,Apr,2026-04-01,22790.0,<NA>,8487218.84,K BIZ,โอนไป X0706 นาย พชรดนัย เนียม++
6,168-2-93045-0,Apr,2026-04-01,1000.0,<NA>,8486218.84,K BIZ,โอนไป KTB X3322 นายณัฐพล นิ่มสุวรร++
7,168-2-93045-0,Apr,2026-04-01,1100.0,<NA>,8485118.84,K BIZ,โอนไป X5893 นาย บุญพิทักษ์ โด++
8,168-2-93045-0,Apr,2026-04-01,115.0,<NA>,8485003.84,K BIZ,โอนไป X3139 นาย วีรพล วงค์น้ำ++
9,168-2-93045-0,Apr,2026-04-01,36016.2,<NA>,8448987.64,K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++
10,168-2-93045-0,Apr,2026-04-01,8287310.5,<NA>,161677.14,K BIZ,โอนไป X5356 บมจ. ซินเน็ค (ประเ++
11,168-2-93045-0,Apr,2026-04-01,24950.0,<NA>,136727.14,K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++
12,168-2-93045-0,Apr,2026-04-01,<NA>,613670.0,750397.14,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
13,168-2-93045-0,Apr,2026-04-02,<NA>,900000.0,1650397.14,K BIZ,จาก X7370 บริษัท ไอ แฮฟ ซีพี++
14,168-2-93045-0,Apr,2026-04-02,<NA>,1700000.0,3350397.14,K BIZ,จาก X8857 บจก. ไอ แฮฟ ซีพี++
15,168-2-93045-0,Apr,2026-04-02,<NA>,4000000.0,7350397.14,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
16,168-2-93045-0,Apr,2026-04-02,3216464.19,<NA>,4133932.95,K BIZ,โอนไป X9717 บมจ. เอสวีโอ++
17,168-2-93045-0,Apr,2026-04-02,7080.0,<NA>,4126852.95,K BIZ,โอนไป KTB X8919 เทศบาลเมืองกระทุ่ม++
18,168-2-93045-0,Apr,2026-04-02,1000.0,<NA>,4125852.95,K BIZ,โอนไป BAY X2413 นาย เติมศักดิ์ จุด++
19,168-2-93045-0,Apr,2026-04-02,6900.0,<NA>,4118952.95,K BIZ,โอนไป BBL X0707 MR JANCOME HABOU++
20,168-2-93045-0,Apr,2026-04-02,1000.0,<NA>,4117952.95,K BIZ,โอนไป X1312 นาย ภูรินทร์ พ่วงช++
21,168-2-93045-0,Apr,2026-04-02,2085.0,<NA>,4115867.95,K BIZ,โอนไป X3866 น.ส. อมรรัตน์ พันเ++
22,168-2-93045-0,Apr,2026-04-02,4300.0,<NA>,4111567.95,K BIZ,โอนไป X2338 ด.ช. ภัทร์นรินท์ แ++
23,168-2-93045-0,Apr,2026-04-02,550.0,<NA>,4111017.95,K BIZ,โอนไป X0094 นาย ลัญจกร เยื้องท++
24,168-2-93045-0,Apr,2026-04-02,52858.0,<NA>,4058159.95,K BIZ,"โอนไป X1761 KASET LATEX CO.,LT++"
25,168-2-93045-0,Apr,2026-04-02,7212.0,<NA>,4050947.95,K BIZ,โอนไป X3130 บจก. ไทม์ แอคเซส โ++
26,168-2-93045-0,Apr,2026-04-02,2000000.0,<NA>,2050947.95,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++
27,168-2-93045-0,Apr,2026-04-02,1500958.68,<NA>,549989.27,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++
28,168-2-93045-0,Apr,2026-04-02,<NA>,348308.0,898297.27,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
29,168-2-93045-0,Apr,2026-04-03,<NA>,3400000.0,4298297.27,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
30,168-2-93045-0,Apr,2026-04-03,62071.53,<NA>,4236225.74,K BIZ,โอนไป X5658 หจก. เอ็นแอนด์พี ท++
31,168-2-93045-0,Apr,2026-04-03,57000.0,<NA>,4179225.74,K BIZ,โอนไป X2003 น.ส. เปรมวดี ลิ้มม++
32,168-2-93045-0,Apr,2026-04-03,57995.0,<NA>,4121230.74,K BIZ,โอนไป BBL X5010 นาง พรเพ็ญ ไซ++
33,168-2-93045-0,Apr,2026-04-03,291897.0,<NA>,3829333.74,K BIZ,โอนไป KK X1562 บริษัท บิวด์เวล ดี++
34,168-2-93045-0,Apr,2026-04-03,127228.26,<NA>,3702105.48,K BIZ,โอนไป KTB X3995 บจ. เอ็ม ทู บี เทร++
35,168-2-93045-0,Apr,2026-04-03,60000.0,<NA>,3642105.48,K BIZ,โอนไป X9366 นาย วัลลภ โชติวงศ์++
36,168-2-93045-0,Apr,2026-04-03,85500.0,<NA>,3556605.48,K BIZ,โอนไป X3651 บจก. มหานครธนภัณ++
37,168-2-93045-0,Apr,2026-04-03,63085.0,<NA>,3493520.48,K BIZ,โอนไป X4449 บมจ. บางจาก คอร์ปอ++
38,168-2-93045-0,Apr,2026-04-03,12900.0,<NA>,3480620.48,K BIZ,โอนไป BAY X0746 บจก. อริยา เอสเ++
39,168-2-93045-0,Apr,2026-04-03,5644.0,<NA>,3474976.48,K BIZ,โอนไป TTB X9005 บจก. ไร่สัณยา (กรุ++
40,168-2-93045-0,Apr,2026-04-03,18202.67,<NA>,3456773.81,K BIZ,โอนไป SCB X8233 บริษัท เจ.ซี.เซ็นต++
41,168-2-93045-0,Apr,2026-04-03,57000.0,<NA>,3399773.81,K BIZ,โอนไป X9990 นาง สุพร รัตนเชษ++
42,168-2-93045-0,Apr,2026-04-03,57000.0,<NA>,3342773.81,K BIZ,โอนไป X1515 น.ส. พรพนา รัตนเชษ++
43,168-2-93045-0,Apr,2026-04-03,91523.52,<NA>,3251250.29,K BIZ,โอนไป SCB X4421 บริษัท เอ็ม ทเวนตี++
44,168-2-93045-0,Apr,2026-04-03,81313.48,<NA>,3169936.81,K BIZ,โอนไป SCB X4858 บริษัท อุดมดี จำก++
45,168-2-93045-0,Apr,2026-04-03,47500.0,<NA>,3122436.81,K BIZ,โอนไป SCB X0653 นาย ปิยะพงศ์ วงษ์++
46,168-2-93045-0,Apr,2026-04-03,71250.0,<NA>,3051186.81,K BIZ,โอนไป TTB X4263 นางสาว นิรดา สุวรร++
47,168-2-93045-0,Apr,2026-04-03,530.0,<NA>,3050656.81,K BIZ,โอนไป SCB X7770 นาย พรชัย ตั้งจริย++
48,168-2-93045-0,Apr,2026-04-03,1000.0,<NA>,3049656.81,K BIZ,โอนไป SCB X3714 นาย ปราชญ์ เพชรไพ++
49,168-2-93045-0,Apr,2026-04-03,90.0,<NA>,3049566.81,K BIZ,โอนไป SCB X2664 นางสาว ศาตนันทน์ พ++

In [72]:
failed_df = pd.DataFrame(failed_files)

print("Failed files:", len(failed_df))

if not failed_df.empty:
    display(failed_df)

Failed files: 0

In [73]:
# เลือก 1 account_number ต่อ 1 month_folder
sample_account_month = (
    kbank_df[
        kbank_df["account_number"].notna()
        & kbank_df["month_folder"].notna()
    ]
    .groupby("month_folder", as_index=False)
    .agg(account_number=("account_number", "first"))
    .sort_values("month_folder")
)

display(sample_account_month)

  month_folder account_number
0          Apr  168-2-93045-0
1          Feb  053-1-97925-7
2          Jan  075-8-56737-0
3         June  053-1-97925-7
4          Mar  168-2-93045-0
5          May  168-2-93045-0

In [74]:
display_columns = [
    "account_number",
    "month_folder",
    "source_file",
    "transaction_date",
    "transaction_type",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "channel",
    "description"
]

for _, row in sample_account_month.iterrows():
    month = row["month_folder"]
    account = row["account_number"]

    sample_df = (
        kbank_df[
            kbank_df["month_folder"].eq(month)
            & kbank_df["account_number"].eq(account)
        ]
        .copy()
        .sort_values(
            ["transaction_date"],
            na_position="first"
        )
    )

    print("=" * 100)
    print(f"MONTH: {month}")
    print(f"ACCOUNT: {account}")
    print(f"ROWS: {len(sample_df):,}")
    print(
        "DATE RANGE:",
        sample_df["transaction_date"].min(),
        "to",
        sample_df["transaction_date"].max()
    )

    display(
        sample_df[
            [
                column
                for column in display_columns
                if column in sample_df.columns
            ]
        ].head(50)
    )

====================================================================================================
MONTH: Apr
ACCOUNT: 168-2-93045-0
ROWS: 383
DATE RANGE: 2026-04-01 00:00:00 to 2026-04-30 00:00:00

,account_number,month_folder,source_file,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
0,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,<NA>,<NA>,9866498.84,NaN,NaN
12,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,<NA>,613670.0,750397.14,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
11,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,24950.0,<NA>,136727.14,K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++
10,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,8287310.5,<NA>,161677.14,K BIZ,โอนไป X5356 บมจ. ซินเน็ค (ประเ++
8,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,115.0,<NA>,8485003.84,K BIZ,โอนไป X3139 นาย วีรพล วงค์น้ำ++
7,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,1100.0,<NA>,8485118.84,K BIZ,โอนไป X5893 นาย บุญพิทักษ์ โด++
9,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,36016.2,<NA>,8448987.64,K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++
5,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,22790.0,<NA>,8487218.84,K BIZ,โอนไป X0706 นาย พชรดนัย เนียม++
4,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,1600.0,<NA>,8510008.84,K BIZ,โอนไป X3734 นาย จิรเดช มีกลิ่น++
3,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,150.0,<NA>,8511608.84,K BIZ,โอนไป X3740 นาย พงศธร อังกูรอั++
2,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,120.0,<NA>,8511758.84,K BIZ,รหัสอ้างอิง KCB13011
1,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,1354620.0,<NA>,8511878.84,K BIZ,โอนไป X7000 CCS ASSET II L++
6,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-01,1000.0,<NA>,8486218.84,K BIZ,โอนไป KTB X3322 นายณัฐพล นิ่มสุวรร++
23,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,550.0,<NA>,4111017.95,K BIZ,โอนไป X0094 นาย ลัญจกร เยื้องท++
28,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,<NA>,348308.0,898297.27,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
27,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,1500958.68,<NA>,549989.27,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++
26,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,2000000.0,<NA>,2050947.95,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++
25,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,7212.0,<NA>,4050947.95,K BIZ,โอนไป X3130 บจก. ไทม์ แอคเซส โ++
24,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,52858.0,<NA>,4058159.95,K BIZ,"โอนไป X1761 KASET LATEX CO.,LT++"
22,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,4300.0,<NA>,4111567.95,K BIZ,โอนไป X2338 ด.ช. ภัทร์นรินท์ แ++
21,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,2085.0,<NA>,4115867.95,K BIZ,โอนไป X3866 น.ส. อมรรัตน์ พันเ++
19,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,6900.0,<NA>,4118952.95,K BIZ,โอนไป BBL X0707 MR JANCOME HABOU++
18,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,1000.0,<NA>,4125852.95,K BIZ,โอนไป BAY X2413 นาย เติมศักดิ์ จุด++
17,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,7080.0,<NA>,4126852.95,K BIZ,โอนไป KTB X8919 เทศบาลเมืองกระทุ่ม++
16,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,3216464.19,<NA>,4133932.95,K BIZ,โอนไป X9717 บมจ. เอสวีโอ++
15,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,<NA>,4000000.0,7350397.14,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
14,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,<NA>,1700000.0,3350397.14,K BIZ,จาก X8857 บจก. ไอ แฮฟ ซีพี++
13,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,<NA>,900000.0,1650397.14,K BIZ,จาก X7370 บริษัท ไอ แฮฟ ซีพี++
20,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-02,1000.0,<NA>,4117952.95,K BIZ,โอนไป X1312 นาย ภูรินทร์ พ่วงช++
45,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,47500.0,<NA>,3122436.81,K BIZ,โอนไป SCB X0653 นาย ปิยะพงศ์ วงษ์++
46,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,71250.0,<NA>,3051186.81,K BIZ,โอนไป TTB X4263 นางสาว นิรดา สุวรร++
47,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,530.0,<NA>,3050656.81,K BIZ,โอนไป SCB X7770 นาย พรชัย ตั้งจริย++
48,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,1000.0,<NA>,3049656.81,K BIZ,โอนไป SCB X3714 นาย ปราชญ์ เพชรไพ++
49,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,90.0,<NA>,3049566.81,K BIZ,โอนไป SCB X2664 นางสาว ศาตนันทน์ พ++
50,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,21100.0,<NA>,3028466.81,K BIZ,โอนไป X2999 น.ส. กิ่งทอง พุทธิ++
55,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,87968.89,<NA>,2847210.12,K BIZ,โอนไป BBL X2988 บจ. เอโอเอส ดีเวลล++
52,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,390.0,<NA>,3026076.81,K BIZ,โอนไป X8797 บจก. คาซ่า ดีไซน์ ++
53,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,44356.0,<NA>,2981720.81,K BIZ,โอนไป X4667 บจก. รักษาความปลอด++
54,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,46541.8,<NA>,2935179.01,K BIZ,โอนไป SCB X4522 บริษัท ซัสโก้ จำกั++
56,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,88211.94,<NA>,2758998.18,K BIZ,โอนไป KTB X6754 บริษัท สมใจประสงค์++
57,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,<NA>,370700.0,3129698.18,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
51,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,2000.0,<NA>,3026466.81,K BIZ,โอนไป X2553 ด.ช. ยศกร ทรงสถิตย++
43,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,91523.52,<NA>,3251250.29,K BIZ,โอนไป SCB X4421 บริษัท เอ็ม ทเวนตี++
44,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,81313.48,<NA>,3169936.81,K BIZ,โอนไป SCB X4858 บริษัท อุดมดี จำก++
33,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,291897.0,<NA>,3829333.74,K BIZ,โอนไป KK X1562 บริษัท บิวด์เวล ดี++
41,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,57000.0,<NA>,3399773.81,K BIZ,โอนไป X9990 นาง สุพร รัตนเชษ++
40,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,18202.67,<NA>,3456773.81,K BIZ,โอนไป SCB X8233 บริษัท เจ.ซี.เซ็นต++
39,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,5644.0,<NA>,3474976.48,K BIZ,โอนไป TTB X9005 บจก. ไร่สัณยา (กรุ++
38,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,12900.0,<NA>,3480620.48,K BIZ,โอนไป BAY X0746 บจก. อริยา เอสเ++
37,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,2026-04-03,63085.0,<NA>,3493520.48,K BIZ,โอนไป X4449 บมจ. บางจาก คอร์ปอ++

====================================================================================================
MONTH: Feb
ACCOUNT: 053-1-97925-7
ROWS: 1,034
DATE RANGE: 2026-02-01 00:00:00 to 2026-02-28 00:00:00

,account_number,month_folder,source_file,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
1437,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,<NA>,3802351.79,NaN,NaN
1458,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,24990.0,4255328.08,K PLUS,จาก X9649 น.ส. ศิรินภา แมดมิ++
1459,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4258328.08,K PLUS,จาก X3686 นาย ณัฐนนท์ สกุลส++
1460,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4261328.08,Internet/Mobile KTB,จาก KTB X5219 MR.YUTTHANAKORN KA++
1461,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,24680.0,4286008.08,K PLUS,จาก X4860 น.ส. ณัฐสุรางค์ อิ++
1462,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,25890.0,4311898.08,Internet/Mobile KTB,จาก KTB X6833 MR.CHADAYU WADAKSO++
1463,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,1000.0,4312898.08,Internet/Mobile KTB,จาก KTB X6833 MR.CHADAYU WADAKSO++
1464,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4315898.08,Internet/Mobile SCB,จาก SCB X8024 นาย อำพล สาดแ++
1465,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4318898.08,K PLUS,จาก X4139 น.ส. สลิลทิพย์ สัจ++
1466,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,18990.0,4337888.08,K PLUS,จาก X9453 น.ส. ธันยพร วิโรจน++
1468,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,250.0,4356288.08,K PLUS,จาก X4860 น.ส. ณัฐสุรางค์ อิ++
1469,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4359288.08,K PLUS,จาก X5952 นาย ชัชวาล ไกรกิจร++
1470,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4362288.08,Internet/Mobile GSB,จาก GSB X5434 นาย วรัตถ์ อ่อนละม++
1471,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,2500.0,4364788.08,Internet/Mobile SCB,จาก SCB X4177 นาย ธนพล สุวรรณเกษ++
1472,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4367788.08,Internet/Mobile KTB,จาก KTB X3261 TANWA JAIY++
1473,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,10000.0,4377788.08,K PLUS,จาก X9668 นาย ทรงวุฒิ มงคลมี++
1457,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,30980.0,4230338.08,K PLUS,จาก X2340 น.ส. กัญญารัตน์ พู++
1456,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,17990.0,4199358.08,K PLUS,จาก X1092 ด.ช. ฉัตรกมล โหมดต++
1467,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,18150.0,4356038.08,K PLUS,จาก X9320 นาย ธัญพิสิษฐ์ กลา++
1454,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4151378.08,Internet/Mobile SCB,จาก SCB X4998 นาย นิธินรรถ เอกะพ++
1455,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,29990.0,4181368.08,K PLUS,จาก X5869 นาย พงศ์ษกร เจริญเ++
1438,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,29710.0,3832061.79,K PLUS,จาก X6592 ด.ช. ปพนพัชร์ ศรีจ++
1439,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,197837.89,4029899.68,K-Cash Connect Plus,จาก X2131 บจก.ช้อปปี้เพย์ (ป++ DIRECT CREDIT R...
1440,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,43058.4,4072958.08,K-Cash Connect Plus,จาก X2131 บจก.ช้อปปี้เพย์ (ป++ DIRECT CREDIT R...
1442,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4076158.08,Internet/Mobile SCB,จาก SCB X6852 นาย พีรญุตม์ ทับท++
1443,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,26990.0,4103148.08,K PLUS,จาก X9002 นาย วัฒนา อุ่นใจ++
1444,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4106148.08,Internet/Mobile BBL,จาก BBL X9440 MR ANUWAT PUNAMY++
1445,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4109148.08,K PLUS,จาก X2347 นาย อานนท์ แยบกสิก++
1441,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,200.0,4073158.08,Internet/Mobile KTB,จาก KTB X6505 MR.KIANGKAI SIRIRA++
1447,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,1490.0,4111638.08,Internet/Mobile KTB,จาก KTB X3920 MISS ROMTEERA MONL++
1448,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,1000.0,4112638.08,K PLUS,จาก X8455 น.ส. ศศิวิมล บุญช++
1449,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4115638.08,K PLUS,จาก X9024 นาย สิทธินนท์ สุคร++
1450,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4118638.08,Internet/Mobile TTB,จาก TTB X0540 FLIGHT FIRST CLASS++
1451,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4121638.08,K PLUS,จาก X3326 นาย พีระพล สีหาบุ++
1452,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,3000.0,4124638.08,K PLUS,จาก X8135 นาย ณัฐนันท์ชัย พล++
1446,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,1000.0,4110148.08,K PLUS,จาก X2051 นาย ธนสาร เวียงนน++
1453,053-1-97925-7,Feb,053.csv,2026-02-01,<NA>,23740.0,4148378.08,Internet/Mobile SCB,จาก SCB X0015 นาย นนทพัทธ์ ราชศร++
1510,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,32890.0,2246634.34,K-Cash Connect Plus,จาก X9588 บจก.ไทย ฟินเ++ DIRECT CREDIT Ref 202...
1509,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,3000.0,2213744.34,Internet/Mobile SCB,จาก SCB X5640 นาง กัณยา มณีวรร++
1508,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,3068.52,2210744.34,K-Cash Connect Plus,จาก X6801 บจก.โอมิเ++ DIRECT CREDIT Ref 202602...
1507,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,3000.0,2207675.82,K PLUS,จาก X4212 นาง นิตยา นาคกระแ++
1504,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,47380.0,2149145.82,Internet/Mobile SCB,จาก SCB X0645 นางสาว วัตถาภรณ์ ต++
1505,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,2490.0,2151635.82,MAKE by KBank,จาก X2813 นาย ธนพล บุญศรีพิท++
1503,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,3000.0,2101765.82,K PLUS,จาก X6739 นาย ชนันท์ธิพัฒน์ ++
1511,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,33390.0,2280024.34,K-Cash Connect Plus,จาก X9588 บจก.ไทย ฟินเ++ DIRECT CREDIT Ref 202...
1502,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,3000.0,2098765.82,Internet/Mobile SCB,จาก SCB X7625 นางสาว พัทธ์ธีรา จ++
1506,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,53040.0,2204675.82,Internet/Mobile KTB,จาก KTB X2742 MISSARISA SAITHO++
1512,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,19590.0,2299614.34,K-Cash Connect Plus,จาก X9588 บจก.ไทย ฟินเ++ DIRECT CREDIT Ref 202...
1521,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,1700.0,2342734.34,Internet/Mobile TTB,จาก TTB X7432 MISS CHALIDA NAKKA++
1514,053-1-97925-7,Feb,053.csv,2026-02-02,<NA>,2490.0,2305104.34,Internet/Mobile SCB,จาก SCB X3220 นาย รัตทพันธ์ รอดม++

====================================================================================================
MONTH: Jan
ACCOUNT: 075-8-56737-0
ROWS: 157
DATE RANGE: 2026-01-01 00:00:00 to 2026-01-31 00:00:00

,account_number,month_folder,source_file,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
3018,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-01,<NA>,<NA>,17600023.55,NaN,NaN
3019,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-01,17000000.0,<NA>,600023.55,K BIZ,โอนไป X0450 บจก. ไอ แฮฟ ซีพี++
3027,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,33693.13,844971.68,โอนเข้า/หักบัญชีอัตโนมัติ,จาก 401013838802001 I HAVE CPU
3025,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,10000.0,718563.55,K PLUS,จาก X4798 นาย ชินาธิป จึงสวน++
3024,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,3000.0,708563.55,Internet/Mobile KTB,จาก KTB X3652 MR.PHAKPOOM RATTAM++
3026,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,92715.0,811278.55,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3022,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,2825.0,701673.55,Internet/Mobile TTB,จาก TTB X8776 MR METHAWI PHAYUNG++
3021,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,48000.0,698848.55,Internet/Mobile TTB,จาก TTB X2887 MR NITHISART SAENG++
3020,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,50825.0,650848.55,Internet/Mobile TTB,จาก TTB X9493 MR NITHISART SAENG++
3023,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-02,<NA>,3890.0,705563.55,K PLUS,จาก X4922 นาย นัท กาฬกาญจ++
3028,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-03,<NA>,3000.0,847971.68,Internet/Mobile BAY,จาก BAY X1951 TULYAWAT SR++
3029,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-03,<NA>,3000.0,850971.68,Internet/Mobile KTB,จาก KTB X0018 PRATAN NANOPSUNTRO++
3030,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-03,<NA>,122470.0,973441.68,K PLUS,จาก X3729 น.ส. กนกอร กอสง่าล++
3031,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-03,<NA>,192100.0,1165541.68,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3032,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-03,<NA>,28762.12,1194303.8,โอนเข้า/หักบัญชีอัตโนมัติ,จาก 401013838802001 I HAVE CPU
3039,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,270838.0,1555766.8,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3040,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,59808.17,1615574.97,โอนเข้า/หักบัญชีอัตโนมัติ,จาก 401013838802001 I HAVE CPU
3038,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,4890.0,1284928.8,Internet/Mobile TTB,จาก TTB X8776 MR METHAWI PHAYUNG++
3037,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,30125.0,1280038.8,Internet/Mobile TTB,จาก TTB X5709 MRS KORAKOT CHAISU++
3035,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,300.0,1226863.8,Internet/Mobile SCB,จาก SCB X1844 นาย เศรษฐกิจ ดวงปิ++
3034,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,29260.0,1226563.8,K BIZ,จาก X6219 บจก. วีเซอร์คิท เอ++
3033,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,3000.0,1197303.8,K BIZ,จาก X6219 บจก. วีเซอร์คิท เอ++
3036,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-04,<NA>,23050.0,1249913.8,Internet/Mobile TTB,จาก TTB X8776 MR METHAWI PHAYUNG++
3041,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-05,<NA>,102925.0,1718499.97,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3042,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-05,<NA>,3163.09,1721663.06,โอนเข้า/หักบัญชีอัตโนมัติ,จาก 401013838802001 I HAVE CPU
3046,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-06,<NA>,350.0,1744943.06,Internet/Mobile SCB,จาก SCB X2339 นางสาว พิราอร พิมพ++
3048,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-06,<NA>,5653.7,1921545.76,โอนเข้า/หักบัญชีอัตโนมัติ,จาก 401013838802001 I HAVE CPU
3047,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-06,<NA>,170949.0,1915892.06,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3045,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-06,<NA>,390.0,1744593.06,K PLUS,จาก X2540 นาย พงศกร ยังบุญส++
3044,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-06,<NA>,21850.0,1744203.06,Internet/Mobile TTB,จาก TTB X3939 MR SIWAPON KLASONG++
3043,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-06,<NA>,690.0,1722353.06,K BIZ,จาก X8053 บจก. เมจิก ไลฟ์ โก++
3049,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-07,<NA>,3000.0,1924545.76,K PLUS,จาก X6797 นาย กนกศักดิ์ แซ่ล++
3050,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-07,<NA>,6490.0,1931035.76,Internet/Mobile SCB,จาก SCB X3777 นาย ภัทรพงศ์ กองสา++
3051,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-07,<NA>,75690.0,2006725.76,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3052,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-07,<NA>,126100.33,2132826.09,โอนเข้า/หักบัญชีอัตโนมัติ,จาก 401013838802001 I HAVE CPU
3060,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,17990.0,2290626.09,Internet/Mobile TTB,จาก TTB X7730 MISS NOOTCHAREE KL++
3059,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,28150.0,2272636.09,Internet/Mobile SCB,จาก SCB X0252 นางสาว ภวิกา คุตน++
3061,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,98250.0,2388876.09,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3058,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,34810.0,2244486.09,Internet/Mobile SCB,จาก SCB X0252 นางสาว ภวิกา คุตน++
3056,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,3000.0,2193686.09,K PLUS,จาก X4092 น.ส. ภวิกา คุตน++
3055,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,3000.0,2190686.09,K PLUS,จาก X4092 น.ส. ภวิกา คุตน++
3054,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,16490.0,2187686.09,Internet/Mobile BBL,จาก BBL X4173 KITJA CHAIPIBAN M++
3053,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,38370.0,2171196.09,Internet/Mobile BAY,จาก BAY X6971 K.U.N.OFFI++
3057,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-08,<NA>,15990.0,2209676.09,Internet/Mobile BAY,จาก BAY X3329 KITTISAK SO++
3062,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-09,<NA>,510.0,2389386.09,K PLUS,จาก X0669 นาย กฤตดนัย ฤกษ์วิ++
3063,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-09,<NA>,3000.0,2392386.09,K PLUS,จาก X8424 นาย ภานุวัตน์ เสรี++
3064,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-09,<NA>,6000.0,2398386.09,Internet/Mobile SCB,จาก SCB X5878 นาย อรัญ สุนทรนัน++
3065,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-09,<NA>,177280.0,2575666.09,EDC/K SHOP/MYQR,จาก 401013838802001 ไอ แฮฟ ซีพียู
3066,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-10,<NA>,600.0,2576266.09,K PLUS,จาก X7230 นาย วิทวัส ธนะชัยว++
3067,075-8-56737-0,Jan,resultFile_20260205_152531.csv,2026-01-10,<NA>,16990.0,2593256.09,K PLUS,จาก X9040 นาย นัฐวัฒน์ ตุงคะ++

====================================================================================================
MONTH: June
ACCOUNT: 053-1-97925-7
ROWS: 976
DATE RANGE: 2026-06-01 00:00:00 to 2026-06-30 00:00:00

,account_number,month_folder,source_file,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
4379,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,<NA>,2001094.7,NaN,NaN
4404,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,22640.0,104393.89,Internet/Mobile KTB,จาก KTB X1539 PLOYPRAPHAT PAN++
4403,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,81753.89,Internet/Mobile KTB,จาก KTB X1539 PLOYPRAPHAT PAN++
4402,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,400.0,78753.89,K PLUS,จาก X4643 น.ส. วิภาสินี สมวง++
4400,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,15990.0,75353.89,K BIZ,จาก X1777 หจก. เกียรติวัฒนาน++
4399,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,90.0,59363.89,K BIZ,จาก X1777 หจก. เกียรติวัฒนาน++
4398,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,45780.0,59273.89,K PLUS,จาก X4951 นาย กัณฑ์อเนก ศกุน++
4397,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,13493.89,Internet/Mobile SCB,จาก SCB X5095 นาย ภาคภูมิ อุป++
4396,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,2000.0,10493.89,K PLUS,จาก X6925 นาย บุรินทร์ ทรัพย++
4395,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,7500000.0,<NA>,8493.89,K BIZ,โอนไป X0450 บจก. ไอ แฮฟ ซีพี++
4394,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,26680.0,7508493.89,Internet/Mobile GSB,จาก GSB X3455 นาย กรกด มิมา++
4393,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,7481813.89,Internet/Mobile SCB,จาก SCB X7120 นาย เติมศักดิ์ ชุม++
4392,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,7478813.89,K PLUS,จาก X7112 ด.ช. สุกฤษฎิ์ ดวงด++
4401,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,78353.89,K PLUS,จาก X4631 นาย กิตติภูมิ พารา++
4390,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,1300.0,7430723.89,Internet/Mobile BBL,จาก BBL X3358 MR KITTISAK SAMAT++
4391,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,45090.0,7475813.89,K PLUS,จาก X6609 นาย พลพัน กอสัมพัน++
4380,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,2004094.7,K PLUS,จาก X0368 นาย กิตติพงษ์ จันท++
4382,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,64285.11,2199473.13,ตู้เติมเงิน / โมบาย แอปพลิเคชัน /เงินโอน,จาก X2131 บจก. ช้อปปี้เพย์ (++
4383,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,4990.0,2204463.13,Internet/Mobile GSB,จาก GSB X3267 นางสาว บุญหลาย แก้++
4384,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,5000000.0,7204463.13,ตู้เติมเงิน / โมบาย แอปพลิเคชัน /เงินโอน,จาก X6801 บจก. โอมิเ++
4381,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,131093.32,2135188.02,ตู้เติมเงิน / โมบาย แอปพลิเคชัน /เงินโอน,จาก X2131 บจก. ช้อปปี้เพย์ (++
4386,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,3000.0,7421393.89,K PLUS,จาก X0235 น.ส. ปิญาภรณ์ ถมปั++
4387,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,4890.0,7426283.89,Internet/Mobile SCB,จาก SCB X2506 นาย ธงชัย จ้อยดวง++
4388,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,500.0,7426783.89,Internet/Mobile BAAC,จาก BAAC X8717 นาย อัครพล บุตรีสุ++
4389,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,2640.0,7429423.89,Internet/Mobile SCB,จาก SCB X1051 นาย สุชาติ วงศ์เจร++
4385,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-01,<NA>,213930.76,7418393.89,ตู้เติมเงิน / โมบาย แอปพลิเคชัน /เงินโอน,จาก X6801 บจก. โอมิเ++
4427,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,1500.0,209780.14,Internet/Mobile BBL,จาก BBL X3358 MR KITTISAK SAMAT++
4434,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,20990.0,273320.14,K BIZ,จาก X9461 บจก. ไอริส เทคโนโล++
4428,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,4770.0,214550.14,Internet/Mobile BAY,จาก BAY X8603 SRIRACHA IN++
4429,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,21290.0,235840.14,K PLUS,จาก X6120 นาย ศราวุธ สิมวิเ++
4430,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,3000.0,238840.14,Internet/Mobile KTB,จาก KTB X4021 MR.THANAKON SUPH++
4431,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,3000.0,241840.14,K PLUS,จาก X7303 น.ส. นารีพิลัย สาส++
4432,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,7490.0,249330.14,Internet/Mobile SCB,จาก SCB X9907 นาย เอกศักดิ์ อิทธ++
4433,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,3000.0,252330.14,Internet/Mobile BBL,จาก BBL X4950 MR NIWAT MALING++
4435,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,499.0,273819.14,K PLUS,จาก X1219 นาย ศิรภัทร ลี้อมร++
4441,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,3000.0,410779.14,K BIZ,จาก X0283 บจก. ว่านไทย เอ็นเ++
4437,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,59380.0,353199.14,Internet/Mobile KTB,จาก KTB X6528 SORAWIT PHUANGPHE++
4438,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,24090.0,377289.14,K-Cash Connect Plus,จาก X3626 บจก.ไทย ฟินเ++ DIRECT CREDIT Ref 202...
4439,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,27490.0,404779.14,K-Cash Connect Plus,จาก X3626 บจก.ไทย ฟินเ++ DIRECT CREDIT Ref 202...
4440,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,3000.0,407779.14,K PLUS,จาก X5049 นาย คีรเทพ จินตนาเ++
4442,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,1490.0,412269.14,Internet/Mobile TTB,จาก TTB X8126 นาย นลธวัช ภิรมณ์++
4443,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,3000.0,415269.14,K PLUS,จาก X7058 น.ส. วารินทร์ รอดเ++
4444,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,31640.0,446909.14,K PLUS,จาก X0629 นาย ธนวัฒน์ แก้วน++
4426,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,34490.0,208280.14,โอนเข้า/หักบัญชีอัตโนมัติ,จาก SMART TTB X6348
4436,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,20000.0,293819.14,K PLUS,จาก X7575 นาย ศักดา แสน++
4425,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,32700.42,173790.14,โอนเข้า/หักบัญชีอัตโนมัติ,"จาก SMART SCB X1622 TRUE MONEY CO.,LT++"
4417,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,4890.0,36299.72,Internet/Mobile SCB,จาก SCB X9574 นาย วรวุฒิ ผาดแผ++
4423,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,22030.0,140889.72,Internet/Mobile BAY,จาก BAY X8026 S SPACE PRO++
4405,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,173538.2,277932.09,โอนเข้า/หักบัญชีอัตโนมัติ,จาก SMART KTB X8883 KRUNG THAI CARD PU++
4406,053-1-97925-7,June,053-ออมทรัพย์.csv,2026-06-02,<NA>,34241.21,312173.3,โอนเข้า/หักบัญชีอัตโนมัติ,จาก SMART BAY X1890 บริษัท บัตรกรุงศรี++

====================================================================================================
MONTH: Mar
ACCOUNT: 168-2-93045-0
ROWS: 414
DATE RANGE: 2026-01-03 00:00:00 to 2026-12-03 00:00:00

,account_number,month_folder,source_file,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
6037,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-01-03,<NA>,<NA>,2181122.78,NaN,NaN
6038,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-01-03,<NA>,662510.0,2843632.78,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6056,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,<NA>,760774.0,5452347.04,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6055,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,1000.0,<NA>,4691573.04,K BIZ,โอนไป KTB X7251 นายภาสกร อดิพงศ์เส++
6054,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,1000.0,<NA>,4692573.04,K BIZ,โอนไป X5610 ด.ช. สรัฐ นันทพิศ++
6053,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,2551750.0,<NA>,4693573.04,K BIZ,โอนไป X9947 บจก. เดอะ ไทธ++
6052,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,657631.76,<NA>,7245323.04,K BIZ,โอนไป X5316 บจก. เทร็คฟิวซั่น ++
6051,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,31030.0,<NA>,7902954.8,K BIZ,โอนไป BBL X2420 บจ. บันเลือง ชินอิ++
6050,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,440225.09,<NA>,7933984.8,K BIZ,โอนไป X0537 บจก. แบ็ค เอ++
6048,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,361553.0,<NA>,8374744.89,K BIZ,โอนไป X7468 บจก. ไวซ์ ปริ้นท์ ++
6049,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,535.0,<NA>,8374209.89,K BIZ,โอนไป X4732 บจก. วี สตอร++
6046,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,1077625.89,<NA>,8757986.89,K BIZ,โอนไป SCB X7881 บริษัท อัลตร้าเทค ++
6045,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,4000.0,<NA>,9835612.78,K BIZ,โอนไป X1282 นาย พงษ์กร ต่วนกระ++
6044,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,410.0,<NA>,9839612.78,K BIZ,โอนไป GSB X5146 นาย อมรเทพ ทาริยะช++
6043,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,1000.0,<NA>,9840022.78,K BIZ,โอนไป พร้อมเพย์ X5954 น.ส. ประภาภรณ์ เฉล++
6042,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,1000.0,<NA>,9841022.78,K BIZ,โอนไป SCB X1596 นาย นิวัตน์ ค้อไ++
6041,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,610.0,<NA>,9842022.78,K BIZ,โอนไป SCB X4109 นาย พิเชฐ ชาไ++
6040,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,1000.0,<NA>,9842632.78,K BIZ,โอนไป BBL X9577 นายสุเมธ ศรีประเส++
6039,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,<NA>,7000000.0,9843632.78,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
6047,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-02-03,21689.0,<NA>,8736297.89,K BIZ,โอนไป BBL X8688 บจ. เอทีที ดิสทริบ++
6057,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-03,<NA>,9000000.0,14452347.04,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
6058,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-03,<NA>,576630.0,15028977.04,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6225,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-13,<NA>,858189.0,7728256.44,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6223,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-13,1000.0,<NA>,6887438.44,K BIZ,โอนไป KTB X9320 นายอัคเรศ เตี๋ยวสก++
6224,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-13,17371.0,<NA>,6870067.44,K BIZ,โอนไป SCB X8371 นาย เบญจพล กิจบุญเ++
6222,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-13,124.6,<NA>,6888438.44,K BIZ,โอนไป X9669 บจก. ชัยเดช โปรเก++
6221,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-13,1000.0,<NA>,6888563.04,K BIZ,โอนไป X7354 บจก. รีช อินดัสทรี++
6230,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-14,<NA>,330843.0,15055999.44,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6226,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-14,1100.0,<NA>,7727156.44,K BIZ,โอนไป SCB X7701 นาย สุรศักดิ์ พิก++
6227,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-14,1000.0,<NA>,7726156.44,K BIZ,โอนไป SCB X7887 นาย ไชยพงศ์ จิรสิน++
6228,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-14,1000.0,<NA>,7725156.44,K BIZ,โอนไป พร้อมเพย์ X2312 นาย นครินทร์ บุญอุ++
6229,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-14,<NA>,7000000.0,14725156.44,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
6231,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-15,<NA>,296851.0,15352850.44,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6237,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,4780.0,<NA>,13356890.09,K BIZ,โอนไป SCB X6704 บริษัท เนสเซ็น ไอท++
6236,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,79500.0,<NA>,13361670.09,K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++
6235,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,166920.0,<NA>,13441170.09,K BIZ,โอนไป BBL X2420 บจ. บันเลือง ชินอิ++
6234,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,8975.0,<NA>,13608090.09,K BIZ,โอนไป X0537 บจก. แบ็ค เอ++
6233,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,22470.0,<NA>,13617065.09,K BIZ,โอนไป X4650 บจก. มัจฉานุ ไดนาม++
6258,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,489661.43,<NA>,8294817.3,K BIZ,โอนไป SCB X7881 บริษัท อัลตร้าเทค ++
6238,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,864158.75,<NA>,12492731.34,K BIZ,โอนไป X5316 บจก. เทร็คฟิวซั่น ++
6261,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,839507.35,<NA>,5801829.39,K BIZ,โอนไป X7468 บจก. ไวซ์ ปริ้นท์ ++
6262,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,<NA>,8000000.0,13801829.39,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
6263,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,<NA>,413090.0,14214919.39,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
6232,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,1713315.35,<NA>,13639535.09,K BIZ,โอนไป X9617 บจก. วีเอสที อีซีเ++
6259,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,1624680.44,<NA>,6670136.86,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++
6239,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,324640.0,<NA>,12168091.34,K BIZ,โอนไป X8504 บจก. โซลสโ++
6241,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,16050.0,<NA>,12130417.34,K BIZ,โอนไป SCB X0283 บริษัท เคพีเอ แพคก++
6257,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,404150.0,<NA>,8784478.73,K BIZ,โอนไป X0487 บจก. อินเทค เทรดดิ++
6256,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,110378.61,<NA>,9188628.73,K BIZ,โอนไป X9684 บจก. โฮม ดิจิตอล ซ++
6255,168-2-93045-0,Mar,กสิกร กระแส.xlsx,2026-03-16,104000.0,<NA>,9299007.34,K BIZ,โอนไป X1639 บจก. ควอนติฟิน คอน++

====================================================================================================
MONTH: May
ACCOUNT: 168-2-93045-0
ROWS: 380
DATE RANGE: 2026-05-01 00:00:00 to 2026-05-31 00:00:00

,account_number,month_folder,source_file,transaction_date,withdrawal,deposit,outstanding_balance,channel,description
7806,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-01,<NA>,<NA>,1754024.33,NaN,NaN
7807,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-01,<NA>,382750.0,2136774.33,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
7817,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,<NA>,220090.0,1329412.13,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
7815,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,1000.0,<NA>,3280621.08,K BIZ,โอนไป X5742 บจก. เอซายน์ กราฟฟ++
7814,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,52563.25,<NA>,3281621.08,K BIZ,โอนไป X9684 บจก. โฮม ดิจิตอล ซ++
7813,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,50.0,<NA>,3334184.33,K BIZ,โอนไป X2321 นาย ตะวัน เยี่ยมจั++
7816,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,2171298.95,<NA>,1109322.13,K BIZ,โอนไป X0474 บจก. เอสเซนตี้ รีซ++
7811,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,50.0,<NA>,3335524.33,K BIZ,โอนไป KTB X7441 น.ส. นันทัชพร คงกะ++
7810,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,200.0,<NA>,3335574.33,K BIZ,โอนไป SCB X8896 น.ส. ปุญญาณัฐ เทพไ++
7809,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,1000.0,<NA>,3335774.33,K BIZ,โอนไป X1078 นาย กานต์ จิระดำ++
7808,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,<NA>,1200000.0,3336774.33,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
7812,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-02,1290.0,<NA>,3334234.33,K BIZ,โอนไป KTB X6757 บริษัท อัลฟ่าเซ็นจ++
7818,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-03,<NA>,319890.0,1649302.13,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
7845,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,3000.0,<NA>,690776.09,K BIZ,โอนไป GSB X5901 นาย นัธทวัฒน์ อภัย++
7839,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,13490.0,<NA>,3622940.47,K BIZ,โอนไป BBL X8219 นาย ยุทธนา สีหะวง++
7840,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,42757.2,<NA>,3580183.27,K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++
7841,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,276836.04,<NA>,3303347.23,K BIZ,โอนไป X9093 บจก. ริชเชซซ++
7842,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,246750.0,<NA>,3056597.23,K BIZ,โอนไป X0487 บจก. อินเทค เทรดดิ++
7843,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,441304.38,<NA>,2615292.85,K BIZ,โอนไป SCB X7881 บริษัท อัลตร้าเทค ++
7844,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1921516.76,<NA>,693776.09,K BIZ,โอนไป X2106 บจก. อินแกรม ไมโคร++
7846,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,15990.0,<NA>,674786.09,K BIZ,โอนไป SCB X6244 นาย กษิดิ์เดช กัญจ++
7852,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,23320.0,<NA>,649267.09,K BIZ,โอนไป BAY X8729 MISS AMPY SIVIL++
7848,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,220.0,<NA>,674437.09,K BIZ,โอนไป X5451 น.ส. ณัฏฐณิชา มณีน++
7849,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,300.0,<NA>,674137.09,K BIZ,โอนไป SCB X7213 นาย วิษณุ ตรีเวทย์++
7850,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1530.0,<NA>,672607.09,K BIZ,โอนไป TTB X9944 นาย ภูริวัฒน์ ถา++
7851,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,20.0,<NA>,672587.09,K BIZ,โอนไป SCB X0092 นาย นัทธภัทร รอบค++
7838,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,15990.0,<NA>,3636430.47,K BIZ,โอนไป KTB X1465 MR. MYINT ZAY THA++
7854,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,40.0,<NA>,648227.09,K BIZ,โอนไป X3919 น.ส. ปานฝัน คำ++
7855,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,<NA>,202865.0,851092.09,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู
7847,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,129.0,<NA>,674657.09,K BIZ,โอนไป พร้อมเพย์ X9252 นาย วรปรัชญ์ สุชาต++
7837,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1000.0,<NA>,3652420.47,K BIZ,โอนไป X2633 นาย ปรมัตถ์ เมืองส++
7853,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1000.0,<NA>,648267.09,K BIZ,โอนไป SCB X2294 นาย ฐิติพันธ์ ทาแก++
7835,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1000.0,<NA>,3654420.47,K BIZ,โอนไป BBL X3439 นาย วัชรวิชญ์ บุรา++
7836,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1000.0,<NA>,3653420.47,K BIZ,โอนไป X0478 นาย วสันต์ชาย แดงส++
7820,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,719553.6,<NA>,7229748.53,K BIZ,โอนไป X5316 บจก. เทร็คฟิวซั่น ++
7821,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,50680.0,<NA>,7179068.53,K BIZ,โอนไป TTB X2938 บจก. ต้าฟาบ๊อก++
7822,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,42630.0,<NA>,7136438.53,K BIZ,โอนไป X9947 บจก. เดอะ ไทธ++
7823,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,1124832.0,<NA>,6011606.53,K BIZ,โอนไป X1983 บจก. จี.เอ็ม.เอส.ค++
7824,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,202900.0,<NA>,5808706.53,K BIZ,โอนไป X2376 บจก. แก็ดเจ็ต วิลล++
7825,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,314079.66,<NA>,5494626.87,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++
7826,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,34903.4,<NA>,5459723.47,K BIZ,โอนไป X5998 บจก. สแกนเนอ++
7819,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,<NA>,6300000.0,7949302.13,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++
7828,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,216482.0,<NA>,4729641.47,K BIZ,โอนไป X8967 บจก. โลกา กรุ++
7829,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,90736.0,<NA>,4638905.47,K BIZ,โอนไป SCB X3871 บริษัท แมดเนส ซิสเ++
7830,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,277344.0,<NA>,4361561.47,K BIZ,โอนไป X4579 บจก. ไพร์ม ท++
7831,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,532350.0,<NA>,3829211.47,K BIZ,โอนไป SCB X1364 บริษัท บี มิวสิก จ++
7832,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,48960.0,<NA>,3780251.47,K BIZ,โอนไป X0537 บจก. แบ็ค เอ++
7833,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,99831.0,<NA>,3680420.47,K BIZ,โอนไป BBL X2420 บจ. บันเลือง ชินอิ++
7834,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,25000.0,<NA>,3655420.47,K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++
7827,168-2-93045-0,May,กสิกร กระแส.csv,2026-05-04,513600.0,<NA>,4946123.47,K BIZ,โอนไป X7468 บจก. ไวซ์ ปริ้นท์ ++

In [75]:
print("Shape:", kbank_df.shape)

print("\nColumns:")
for index, column in enumerate(kbank_df.columns):
    print(index, repr(column))

print("\nData types:")
print(kbank_df.dtypes)

print("\nNull percentage:")
display(
    kbank_df.isna()
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
    .to_frame("null_percent")
)

Shape: (9320, 14)

Columns:
0 'bank'
1 'account_number'
2 'month_folder'
3 'source_file'
4 'source_path'
5 'transaction_date'
6 'withdrawal'
7 'deposit'
8 'outstanding_balance'
9 'channel'
10 'description'
11 'เวลา/วันที่ ทำรายการ'
12 'รายการ'
13 'เวลา/ วันที่มีผล'

Data types:
bank                               str
account_number                     str
month_folder                       str
source_file                        str
source_path                        str
transaction_date        datetime64[us]
withdrawal                     Float64
deposit                        Float64
outstanding_balance            Float64
channel                            str
description                        str
เวลา/วันที่ ทำรายการ               str
รายการ                             str
เวลา/ วันที่มีผล                   str
dtype: object

Null percentage:

                      null_percent
withdrawal                   79.95
เวลา/วันที่ ทำรายการ         79.57
เวลา/ วันที่มีผล             20.68
deposit                      20.30
channel                       0.25
description                   0.25
transaction_date              0.00
source_path                   0.00
source_file                   0.00
month_folder                  0.00
account_number                0.00
bank                          0.00
outstanding_balance           0.00
รายการ                        0.00

In [76]:
# ทำความสะอาดชื่อคอลัมน์ก่อน
kbank_df.columns = (
    kbank_df.columns
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

rename_map = {
    "เวลา/วันที่ ทำรายการ": "transaction_time",
    "เวลา / วันที่ทำรายการ": "transaction_time",
    "รายการ": "transaction_type",
    "เวลา/วันที่มีผล": "effective_time",
    "เวลา/ วันที่มีผล": "effective_time",
}

kbank_df = kbank_df.rename(columns=rename_map)

In [77]:
print(kbank_df.columns.tolist())

['bank', 'account_number', 'month_folder', 'source_file', 'source_path', 'transaction_date', 'withdrawal', 'deposit', 'outstanding_balance', 'channel', 'description', 'transaction_time', 'transaction_type', 'effective_time']

In [78]:
kbank_df["transaction_date"] = pd.to_datetime(
    kbank_df["transaction_date"],
    format="%d-%m-%y",
    errors="coerce"
)

In [79]:
for column in ["transaction_time", "effective_time"]:
    if column in kbank_df.columns:
        kbank_df[column] = (
            kbank_df[column]
            .astype("string")
            .str.strip()
            .replace({
                "": pd.NA,
                "nan": pd.NA,
                "NaN": pd.NA
            })
        )

In [80]:
amount_columns = [
    "withdrawal",
    "deposit",
    "outstanding_balance"
]

for column in amount_columns:
    if column in kbank_df.columns:
        kbank_df[column] = (
            kbank_df[column]
            .astype("string")
            .str.replace(",", "", regex=False)
            .str.strip()
            .replace({
                "": pd.NA,
                "nan": pd.NA,
                "NaN": pd.NA,
                "#####": pd.NA
            })
        )

        kbank_df[column] = pd.to_numeric(
            kbank_df[column],
            errors="coerce"
        )

In [81]:
preferred_columns = [
    "bank",
    "account_number",
    "month_folder",
    "source_file",
    "source_path",
    "transaction_date",
    "transaction_time",
    "transaction_type",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "channel",
    "description",
    "effective_time"
]

existing_columns = [
    column
    for column in preferred_columns
    if column in kbank_df.columns
]

remaining_columns = [
    column
    for column in kbank_df.columns
    if column not in existing_columns
]

kbank_df = kbank_df[
    existing_columns + remaining_columns
].copy()

In [82]:
display_columns = [
    "account_number",
    "month_folder",
    "transaction_date",
    "transaction_time",
    "transaction_type",
    "withdrawal",
    "deposit",
    "outstanding_balance",
    "channel",
    "description",
    "effective_time"
]

display(
    kbank_df[
        [
            column
            for column in display_columns
            if column in kbank_df.columns
        ]
    ].head(30)
)

,account_number,month_folder,transaction_date,transaction_time,transaction_type,withdrawal,deposit,outstanding_balance,channel,description,effective_time
0,168-2-93045-0,Apr,2026-04-01,<NA>,ยอดยกมา,<NA>,<NA>,9866498.84,NaN,NaN,<NA>
1,168-2-93045-0,Apr,2026-04-01,10:00,โอนเงิน,1354620.0,<NA>,8511878.84,K BIZ,โอนไป X7000 CCS ASSET II L++,<NA>
2,168-2-93045-0,Apr,2026-04-01,10:00,ค่าธรรมเนียม,120.0,<NA>,8511758.84,K BIZ,รหัสอ้างอิง KCB13011,<NA>
3,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,150.0,<NA>,8511608.84,K BIZ,โอนไป X3740 นาย พงศธร อังกูรอั++,<NA>
4,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,1600.0,<NA>,8510008.84,K BIZ,โอนไป X3734 นาย จิรเดช มีกลิ่น++,<NA>
5,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,22790.0,<NA>,8487218.84,K BIZ,โอนไป X0706 นาย พชรดนัย เนียม++,<NA>
6,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,1000.0,<NA>,8486218.84,K BIZ,โอนไป KTB X3322 นายณัฐพล นิ่มสุวรร++,<NA>
7,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,1100.0,<NA>,8485118.84,K BIZ,โอนไป X5893 นาย บุญพิทักษ์ โด++,<NA>
8,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,115.0,<NA>,8485003.84,K BIZ,โอนไป X3139 นาย วีรพล วงค์น้ำ++,<NA>
9,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,36016.2,<NA>,8448987.64,K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++,<NA>
10,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,8287310.5,<NA>,161677.14,K BIZ,โอนไป X5356 บมจ. ซินเน็ค (ประเ++,<NA>
11,168-2-93045-0,Apr,2026-04-01,13:37,โอนเงิน,24950.0,<NA>,136727.14,K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++,<NA>
12,168-2-93045-0,Apr,2026-04-01,23:19,รับเงินจากการขายด้วย Thai QR Payment,<NA>,613670.0,750397.14,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,<NA>
13,168-2-93045-0,Apr,2026-04-02,12:31,รับโอนเงิน,<NA>,900000.0,1650397.14,K BIZ,จาก X7370 บริษัท ไอ แฮฟ ซีพี++,<NA>
14,168-2-93045-0,Apr,2026-04-02,12:31,รับโอนเงิน,<NA>,1700000.0,3350397.14,K BIZ,จาก X8857 บจก. ไอ แฮฟ ซีพี++,<NA>
15,168-2-93045-0,Apr,2026-04-02,12:31,รับโอนเงิน,<NA>,4000000.0,7350397.14,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,<NA>
16,168-2-93045-0,Apr,2026-04-02,13:58,โอนเงิน,3216464.19,<NA>,4133932.95,K BIZ,โอนไป X9717 บมจ. เอสวีโอ++,<NA>
17,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,7080.0,<NA>,4126852.95,K BIZ,โอนไป KTB X8919 เทศบาลเมืองกระทุ่ม++,<NA>
18,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,1000.0,<NA>,4125852.95,K BIZ,โอนไป BAY X2413 นาย เติมศักดิ์ จุด++,<NA>
19,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,6900.0,<NA>,4118952.95,K BIZ,โอนไป BBL X0707 MR JANCOME HABOU++,<NA>
20,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,1000.0,<NA>,4117952.95,K BIZ,โอนไป X1312 นาย ภูรินทร์ พ่วงช++,<NA>
21,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,2085.0,<NA>,4115867.95,K BIZ,โอนไป X3866 น.ส. อมรรัตน์ พันเ++,<NA>
22,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,4300.0,<NA>,4111567.95,K BIZ,โอนไป X2338 ด.ช. ภัทร์นรินท์ แ++,<NA>
23,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,550.0,<NA>,4111017.95,K BIZ,โอนไป X0094 นาย ลัญจกร เยื้องท++,<NA>
24,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,52858.0,<NA>,4058159.95,K BIZ,"โอนไป X1761 KASET LATEX CO.,LT++",<NA>
25,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,7212.0,<NA>,4050947.95,K BIZ,โอนไป X3130 บจก. ไทม์ แอคเซส โ++,<NA>
26,168-2-93045-0,Apr,2026-04-02,14:02,โอนเงิน,2000000.0,<NA>,2050947.95,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,<NA>
27,168-2-93045-0,Apr,2026-04-02,14:47,โอนเงิน,1500958.68,<NA>,549989.27,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,<NA>
28,168-2-93045-0,Apr,2026-04-02,23:18,รับเงินจากการขายด้วย Thai QR Payment,<NA>,348308.0,898297.27,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,<NA>
29,168-2-93045-0,Apr,2026-04-03,10:07,รับโอนเงิน,<NA>,3400000.0,4298297.27,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,<NA>

In [83]:
kbank_df["bank"] = "KBANK"
if "bank" in kbank_df.columns:
    kbank_df = kbank_df.drop(columns=["bank"])

kbank_df.insert(0, "bank", "KBANK")

In [84]:
display(kbank_df.head(30))

,bank,account_number,month_folder,source_file,source_path,transaction_date,transaction_time,transaction_type,withdrawal,deposit,outstanding_balance,channel,description,effective_time
0,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,<NA>,ยอดยกมา,<NA>,<NA>,9866498.84,NaN,NaN,<NA>
1,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,10:00,โอนเงิน,1354620.0,<NA>,8511878.84,K BIZ,โอนไป X7000 CCS ASSET II L++,<NA>
2,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,10:00,ค่าธรรมเนียม,120.0,<NA>,8511758.84,K BIZ,รหัสอ้างอิง KCB13011,<NA>
3,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,150.0,<NA>,8511608.84,K BIZ,โอนไป X3740 นาย พงศธร อังกูรอั++,<NA>
4,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,1600.0,<NA>,8510008.84,K BIZ,โอนไป X3734 นาย จิรเดช มีกลิ่น++,<NA>
5,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,22790.0,<NA>,8487218.84,K BIZ,โอนไป X0706 นาย พชรดนัย เนียม++,<NA>
6,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,1000.0,<NA>,8486218.84,K BIZ,โอนไป KTB X3322 นายณัฐพล นิ่มสุวรร++,<NA>
7,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,1100.0,<NA>,8485118.84,K BIZ,โอนไป X5893 นาย บุญพิทักษ์ โด++,<NA>
8,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,115.0,<NA>,8485003.84,K BIZ,โอนไป X3139 นาย วีรพล วงค์น้ำ++,<NA>
9,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,36016.2,<NA>,8448987.64,K BIZ,โอนไป X3861 บมจ. อินเทอร์เน็ตป++,<NA>
10,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,8287310.5,<NA>,161677.14,K BIZ,โอนไป X5356 บมจ. ซินเน็ค (ประเ++,<NA>
11,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,13:37,โอนเงิน,24950.0,<NA>,136727.14,K BIZ,โอนไป X3069 บจก. นีโอลูชั่น เท++,<NA>
12,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-01,23:19,รับเงินจากการขายด้วย Thai QR Payment,<NA>,613670.0,750397.14,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,<NA>
13,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,12:31,รับโอนเงิน,<NA>,900000.0,1650397.14,K BIZ,จาก X7370 บริษัท ไอ แฮฟ ซีพี++,<NA>
14,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,12:31,รับโอนเงิน,<NA>,1700000.0,3350397.14,K BIZ,จาก X8857 บจก. ไอ แฮฟ ซีพี++,<NA>
15,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,12:31,รับโอนเงิน,<NA>,4000000.0,7350397.14,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,<NA>
16,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,13:58,โอนเงิน,3216464.19,<NA>,4133932.95,K BIZ,โอนไป X9717 บมจ. เอสวีโอ++,<NA>
17,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,7080.0,<NA>,4126852.95,K BIZ,โอนไป KTB X8919 เทศบาลเมืองกระทุ่ม++,<NA>
18,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,1000.0,<NA>,4125852.95,K BIZ,โอนไป BAY X2413 นาย เติมศักดิ์ จุด++,<NA>
19,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,6900.0,<NA>,4118952.95,K BIZ,โอนไป BBL X0707 MR JANCOME HABOU++,<NA>
20,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,1000.0,<NA>,4117952.95,K BIZ,โอนไป X1312 นาย ภูรินทร์ พ่วงช++,<NA>
21,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,2085.0,<NA>,4115867.95,K BIZ,โอนไป X3866 น.ส. อมรรัตน์ พันเ++,<NA>
22,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,4300.0,<NA>,4111567.95,K BIZ,โอนไป X2338 ด.ช. ภัทร์นรินท์ แ++,<NA>
23,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,550.0,<NA>,4111017.95,K BIZ,โอนไป X0094 นาย ลัญจกร เยื้องท++,<NA>
24,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,52858.0,<NA>,4058159.95,K BIZ,"โอนไป X1761 KASET LATEX CO.,LT++",<NA>
25,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,7212.0,<NA>,4050947.95,K BIZ,โอนไป X3130 บจก. ไทม์ แอคเซส โ++,<NA>
26,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:02,โอนเงิน,2000000.0,<NA>,2050947.95,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,<NA>
27,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,14:47,โอนเงิน,1500958.68,<NA>,549989.27,K BIZ,โอนไป UOBT X6998 บมจ. เอสไอเอสดิสทร++,<NA>
28,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-02,23:18,รับเงินจากการขายด้วย Thai QR Payment,<NA>,348308.0,898297.27,EDC/K SHOP/MYQR,จาก KB000001793643 ไอ แฮฟ ซีพียู,<NA>
29,KBANK,168-2-93045-0,Apr,กสิกร-กระแสรายวัน.csv,Apr\กสิกร-กระแสรายวัน.csv,2026-04-03,10:07,รับโอนเงิน,<NA>,3400000.0,4298297.27,K BIZ,จาก X9257 บจก. ไอ แฮฟ ซีพี++,<NA>

In [85]:
amount_columns = [
    "withdrawal",
    "deposit",
    "outstanding_balance"
]

for column in amount_columns:
    kbank_df[column] = (
        kbank_df[column]
        .astype("string")
        .str.replace(",", "", regex=False)
        .str.strip()
        .replace({
            "": pd.NA,
            "nan": pd.NA,
            "NaN": pd.NA,
            "<NA>": pd.NA,
            "#####": pd.NA
        })
    )

    kbank_df[column] = pd.to_numeric(
        kbank_df[column],
        errors="coerce"
    )

In [86]:
kbank_df[amount_columns] = (
    kbank_df[amount_columns]
    .astype("Float64")
)

In [87]:
print(kbank_df[amount_columns].dtypes)

display(
    kbank_df[
        [
            "withdrawal",
            "deposit",
            "outstanding_balance"
        ]
    ].head(30)
)

withdrawal             Float64
deposit                Float64
outstanding_balance    Float64
dtype: object

    withdrawal    deposit  outstanding_balance
0         <NA>       <NA>           9866498.84
1    1354620.0       <NA>           8511878.84
2        120.0       <NA>           8511758.84
3        150.0       <NA>           8511608.84
4       1600.0       <NA>           8510008.84
5      22790.0       <NA>           8487218.84
6       1000.0       <NA>           8486218.84
7       1100.0       <NA>           8485118.84
8        115.0       <NA>           8485003.84
9      36016.2       <NA>           8448987.64
10   8287310.5       <NA>            161677.14
11     24950.0       <NA>            136727.14
12        <NA>   613670.0            750397.14
13        <NA>   900000.0           1650397.14
14        <NA>  1700000.0           3350397.14
15        <NA>  4000000.0           7350397.14
16  3216464.19       <NA>           4133932.95
17      7080.0       <NA>           4126852.95
18      1000.0       <NA>           4125852.95
19      6900.0       <NA>           4118952.95
20      1000.0       <NA>           4117952.95
21      2085.0       <NA>           4115867.95
22      4300.0       <NA>           4111567.95
23       550.0       <NA>           4111017.95
24     52858.0       <NA>           4058159.95
25      7212.0       <NA>           4050947.95
26   2000000.0       <NA>           2050947.95
27  1500958.68       <NA>            549989.27
28        <NA>   348308.0            898297.27
29        <NA>  3400000.0           4298297.27

In [88]:
# Check dtype for every column
print(kbank_df.dtypes)

bank                              str
account_number                    str
month_folder                      str
source_file                       str
source_path                       str
transaction_date       datetime64[us]
transaction_time               string
transaction_type                  str
withdrawal                    Float64
deposit                       Float64
outstanding_balance           Float64
channel                           str
description                       str
effective_time                 string
dtype: object